var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var e=0;return function(){return e<c.length?{done:!1,value:c[e++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.makeIterator=function(c){var e="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return e?e.call(c):$jscomp.arrayIterator(c)};
$jscomp.getGlobal=function(c){c=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,c];for(var e=0;e<c.length;++e){var h=c[e];if(h&&h.Math==Math)return h}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,h){c!=Array.prototype&&c!=Object.prototype&&(c[e]=h.value)};$jscomp.polyfill=function(c,e,h,q){if(e){h=$jscomp.global;c=c.split(".");for(q=0;q<c.length-1;q++){var D=c[q];D in h||(h[D]={});h=h[D]}c=c[c.length-1];q=h[c];e=e(q);e!=q&&null!=e&&$jscomp.defineProperty(h,c,{configurable:!0,writable:!0,value:e})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function e(){this.batch_=null}function h(c){return c instanceof D?c:new D(function(e,xc){e(c)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;e.prototype.asyncExecute=function(c){if(null==this.batch_){this.batch_=[];var e=this;this.asyncExecuteFunction(function(){e.executeBatch_()})}this.batch_.push(c)};var q=$jscomp.global.setTimeout;e.prototype.asyncExecuteFunction=function(c){q(c,0)};e.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=
this.batch_;this.batch_=[];for(var e=0;e<c.length;++e){var h=c[e];c[e]=null;try{h()}catch(na){this.asyncThrow_(na)}}}this.batch_=null};e.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var D=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var e=this.createResolveAndReject_();try{c(e.resolve,e.reject)}catch(lb){e.reject(lb)}};D.prototype.createResolveAndReject_=function(){function c(c){return function(xc){h||(h=!0,c.call(e,xc))}}var e=this,
h=!1;return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};D.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof D)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var e=null!=c;break a;case "function":e=!0;break a;default:e=!1}e?this.resolveToNonPromiseObj_(c):this.fulfill_(c)}};D.prototype.resolveToNonPromiseObj_=function(c){var e=void 0;try{e=c.then}catch(lb){this.reject_(lb);return}"function"==
typeof e?this.settleSameAsThenable_(e,c):this.fulfill_(c)};D.prototype.reject_=function(c){this.settle_(2,c)};D.prototype.fulfill_=function(c){this.settle_(1,c)};D.prototype.settle_=function(c,e){if(0!=this.state_)throw Error("Cannot settle("+c+", "+e+"): Promise already settled in state"+this.state_);this.state_=c;this.result_=e;this.executeOnSettledCallbacks_()};D.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var c=0;c<this.onSettledCallbacks_.length;++c)Hb.asyncExecute(this.onSettledCallbacks_[c]);
this.onSettledCallbacks_=null}};var Hb=new e;D.prototype.settleSameAsPromise_=function(c){var e=this.createResolveAndReject_();c.callWhenSettled_(e.resolve,e.reject)};D.prototype.settleSameAsThenable_=function(c,e){var h=this.createResolveAndReject_();try{c.call(e,h.resolve,h.reject)}catch(na){h.reject(na)}};D.prototype.then=function(c,e){function h(c,e){return"function"==typeof c?function(e){try{q(c(e))}catch(Ib){Z(Ib)}}:e}var q,Z,xc=new D(function(c,e){q=c;Z=e});this.callWhenSettled_(h(c,q),h(e,
Z));return xc};D.prototype.catch=function(c){return this.then(void 0,c)};D.prototype.callWhenSettled_=function(c,e){function h(){switch(q.state_){case 1:c(q.result_);break;case 2:e(q.result_);break;default:throw Error("Unexpected state: "+q.state_);}}var q=this;null==this.onSettledCallbacks_?Hb.asyncExecute(h):this.onSettledCallbacks_.push(h)};D.resolve=h;D.reject=function(c){return new D(function(e,h){h(c)})};D.race=function(c){return new D(function(e,q){for(var D=$jscomp.makeIterator(c),Z=D.next();!Z.done;Z=
D.next())h(Z.value).callWhenSettled_(e,q)})};D.all=function(c){var e=$jscomp.makeIterator(c),q=e.next();return q.done?h([]):new D(function(c,D){function Z(e){return function(h){na[e]=h;Oa--;0==Oa&&c(na)}}var na=[],Oa=0;do na.push(void 0),Oa++,h(q.value).callWhenSettled_(Z(na.length-1),D),q=e.next();while(!q.done)})};return D},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(c,e){this.$jscomp$symbol$id_=c;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:e})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function c(h){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(h||"")+"_"+e++,h)}var e=0;return c}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.asyncIterator;c||(c=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.underscoreProtoCanBeSet=function(){var c={a:!0},e={};try{return e.__proto__=c,e.a}catch(h){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(c,e){c.__proto__=e;if(c.__proto__!==e)throw new TypeError(c+" is not extensible");return c}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(c){if(!(c instanceof Object))throw new TypeError("Iterator result "+c+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(c){this.yieldResult=c};$jscomp.generator.Context.prototype.throw_=function(c){this.abruptCompletion_={exception:c,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(c){this.abruptCompletion_={return:c};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(c){this.abruptCompletion_={jumpTo:c};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(c,e){this.nextAddress=e;return{value:c}};$jscomp.generator.Context.prototype.yieldAll=function(c,e){c=$jscomp.makeIterator(c);var h=c.next();$jscomp.generator.ensureIteratorResultIsObject_(h);if(h.done)this.yieldResult=h.value,this.nextAddress=e;else return this.yieldAllIterator_=c,this.yield(h.value,e)};
$jscomp.generator.Context.prototype.jumpTo=function(c){this.nextAddress=c};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(c,e){this.catchAddress_=c;void 0!=e&&(this.finallyAddress_=e)};$jscomp.generator.Context.prototype.setFinallyBlock=function(c){this.catchAddress_=0;this.finallyAddress_=c||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(c,e){this.nextAddress=c;this.catchAddress_=e||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(c){this.catchAddress_=c||0;c=this.abruptCompletion_.exception;this.abruptCompletion_=null;return c};$jscomp.generator.Context.prototype.enterFinallyBlock=function(c,e,h){h?this.finallyContexts_[h]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=c||0;this.finallyAddress_=e||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(c,e){e=this.finallyContexts_.splice(e||0)[0];if(e=this.abruptCompletion_=this.abruptCompletion_||e){if(e.isException)return this.jumpToErrorHandler_();void 0!=e.jumpTo&&this.finallyAddress_<e.jumpTo?(this.nextAddress=e.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=c};$jscomp.generator.Context.prototype.forIn=function(c){return new $jscomp.generator.Context.PropertyIterator(c)};
$jscomp.generator.Context.PropertyIterator=function(c){this.object_=c;this.properties_=[];for(var e in c)this.properties_.push(e);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var c=this.properties_.pop();if(c in this.object_)return c}return null};$jscomp.generator.Engine_=function(c){this.context_=new $jscomp.generator.Context;this.program_=c};
$jscomp.generator.Engine_.prototype.next_=function(c){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,c,this.context_.next_);this.context_.next_(c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(c){this.context_.start_();var e=this.context_.yieldAllIterator_;if(e)return this.yieldAllStep_("return"in e?e["return"]:function(c){return{value:c,done:!0}},c,this.context_.return);this.context_.return(c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(c){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],c,this.context_.next_);this.context_.throw_(c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(c,e,h){try{var q=c.call(this.context_.yieldAllIterator_,e);$jscomp.generator.ensureIteratorResultIsObject_(q);if(!q.done)return this.context_.stop_(),q;var D=q.value}catch(Hb){return this.context_.yieldAllIterator_=null,this.context_.throw_(Hb),this.nextStep_()}this.context_.yieldAllIterator_=null;h.call(this.context_,D);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var c=this.program_(this.context_);if(c)return this.context_.stop_(),{value:c.value,done:!1}}catch(e){this.context_.yieldResult=void 0,this.context_.throw_(e)}this.context_.stop_();if(this.context_.abruptCompletion_){c=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(c.isException)throw c.exception;return{value:c.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(c){this.next=function(e){return c.next_(e)};this.throw=function(e){return c.throw_(e)};this.return=function(e){return c.return_(e)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(c,e){e=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(e));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(e,c.prototype);return e};
$jscomp.asyncExecutePromiseGenerator=function(c){function e(e){return c.next(e)}function h(e){return c.throw(e)}return new Promise(function(q,D){function Hb(c){c.done?q(c.value):Promise.resolve(c.value).then(e,h).then(Hb,D)}Hb(c.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(c){return $jscomp.asyncExecutePromiseGenerator(c())};$jscomp.asyncExecutePromiseGeneratorProgram=function(c){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(c)))};
$jscomp.iteratorFromArray=function(c,e){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var h=0,q={next:function(){if(h<c.length){var D=h++;return{value:e(D,c[D]),done:!1}}q.next=function(){return{done:!0,value:void 0}};return q.next()}};q[Symbol.iterator]=function(){return q};return q};
$jscomp.polyfill("Array.prototype.fill",function(c){return c?c:function(c,h,q){var e=this.length||0;0>h&&(h=Math.max(0,e+h));if(null==q||q>e)q=e;q=Number(q);0>q&&(q=Math.max(0,e+q));for(h=Number(h||0);h<q;h++)this[h]=c;return this}},"es6","es3");
function PEvs(c,e,h,q,D,Hb,xc){var Z,lb,na,Te,vd,Wf,Oa,Xb,Ib,ea,mb,Jb=0,Yb=0,ie,Pa=!1,yc=!1,Zb=0,nb=0,$b=0,rb=0,wd,Pc,je=3,ac=function(c){Oa=c.target;for(Ib=Xb=0;Oa;)Xb+=Oa.offsetLeft-Oa.scrollLeft,Ib+=Oa.offsetTop-Oa.scrollTop,Oa=Oa.offsetParent;Jb=(Pa?wd:c.pageX)-Xb-document.body.scrollLeft;Yb=(Pa?Pc:c.pageY)-Ib-document.body.scrollTop};this.getX=function(){return Jb};this.getY=function(){return Yb};this.setHysteresis=function(c){je=c};var E=function(c){c.preventDefault();c.stopImmediatePropagation?
c.stopImmediatePropagation():c.stopPropagation()},ke=function(c){ac(c);ie=Jb;xa=Yb;U=!0;null!=fa&&(Te=(new Date).getTime());null!=oa&&oa(c)},I=function(c){U&&(ac(c),U=!1,null!=sb&&sb(c),null!=fa&&(vd=(new Date).getTime(),Wf=vd-Te,300>Wf&&fa(c)))},Ka=function(c){ac(c);Math.abs(Jb-ie)<je&&Math.abs(Yb-xa)<je||(xa=ie=-9999,U?null!=Wa&&Wa(c):null!=ob&&ob(c),null!=le&&Ue())};this.touchDown=function(c){na=!0;if(1<c.targetTouches.length)return Pa=!0,mb&&(nb=-1,E(c)),!1;Z=c.changedTouches;lb=Z[0];ke(lb)};
this.touchUp=function(c){0==c.targetTouches.length&&(Pa=na=!1);E(c);if(Pa||yc)return Pa||(yc=!1),!1;Z=c.changedTouches;lb=Z[0];I(lb)};this.touchMove=function(c){na=!0;E(c);if(Pa)return mb&&(Z=c.targetTouches,wd=(Z[0].pageX+Z[1].pageX)/2,Pc=(Z[0].pageY+Z[1].pageY)/2,yc=!0,$b=Z[0].pageX-Z[1].pageX,rb=Z[0].pageY-Z[1].pageY,Zb=$b*$b+rb*rb,ac(c),mb&&0<nb&&30<Math.abs(Zb-nb)&&mb(0<Zb-nb?1:-1),nb=Zb),!1;Z=c.changedTouches;lb=Z[0];Ka(lb)};this.pointUp=function(c){E(c);for(var e=0;e<ya.length;e++)if(ya[e].pointerId==
c.pointerId){ya.splice(e,1);break}0==ya.length&&(na=Pa=!1);if(Pa||yc)return Pa||(yc=!1),!1;I(c);return!1};this.pointDown=function(c){E(c);ya.push(c);nb=-1;na=!0;1<ya.length?Pa=!0:ke(c);return!1};this.pointMove=function(c){E(c);for(var e=0;e<ya.length;e++)ya[e].pointerId==c.pointerId&&(ya[e]=c);if(Pa||!yc){if(Pa)return wd=(ya[0].pageX+ya[1].pageX)/2,Pc=(ya[0].pageY+ya[1].pageY)/2,ac(c),mb&&(yc=!0,$b=ya[0].pageX-ya[1].pageX,rb=ya[0].pageY-ya[1].pageY,Zb=$b*$b+rb*rb,mb&&0<nb&&30<Math.abs(Zb-nb)&&mb(0<
Zb-nb?1:-1),nb=Zb),!1;Ka(c);return!1}};this.mouseDown=function(c){na||(E(c),ke(c))};this.clearDown=function(){U=!1};this.mouseUp=function(c){na||(E(c),I(c))};this.useWheel=function(e){c.addEventListener("wheel",this.mouseWheel,!0);mb=e};this.mouseWheel=function(c){ac(c);var e=Math.max(-1,Math.min(1,-c.deltaY||-c.detail));E(c);mb&&mb(e)};this.mouseClick=function(c){E(c);U=!1};this.mouseMove=function(c){na||(E(c),Ka(c))};this.mouseDragged=function(c){na||(E(c),ac(c),null!=Wa&&Wa(c),null!=le&&Ue())};
var Ue=function(){clearTimeout(ea);ea=setTimeout(function(){le()},600)};var xa=ie=Yb=Jb=0;var oa=e;var sb=h;var ob=q;var Wa=D;var fa=Hb;var le=xc;var U=na=!1;var ya=[];c.addEventListener("mousedown",this.mouseDown,!1);c.addEventListener("mouseup",this.mouseUp,!1);c.addEventListener("mousemove",this.mouseMove,!1);c.addEventListener("click",this.mouseClick,!1);c.addEventListener("touchstart",this.touchDown,!1);c.addEventListener("touchend",this.touchUp,!1);c.addEventListener("touchmove",this.touchMove,
!1);c.addEventListener("touchleave",this.touchUp,!1);c.addEventListener("touchcancel",this.touchUp,!1);c.addEventListener("contextmenu",function(c){c.preventDefault()},!1);c.style["touch-action"]="none";c.addEventListener("mouseout",function(c){U||(Yb=Jb=-1,null!=ob&&ob(c));U=!1})};var HAniSF=function(){function c(b){var a,g;xd=!0;if(b instanceof Array)for(f={},null!=ph&&(b=b.concat(ph)),a=0;a<b.length;a++){if(!(2>b[a].length)){var d=b[a].trim();if(0!=d.indexOf("#")){var c=d.indexOf("=");if(!(1>c)){var R=d.substr(0,c).trim().toLowerCase();f[R]=d.substr(c+1).trim()}}}}else f=b;Ve=!1;a=f.debug;null!=a&&("true"==a?(Xf=window.open("","HAniSDebugInfo","scrollbars=yes,width=400,height=200"),Ve=!0,ha("HAniS Version 4.44")):Ve=!1);a=f.no_initial_focus;null!=a&&"false"!=a||u.focus();
pb=!0;z(f.set_className,"f")&&(pb=!1);ha("Is type of param an array = "+(b instanceof Array));a=f.divalign;null!=a&&(me=a.trim(),u.align=me);z(f.prevent_shortcuts,"t")&&(We=!0);a=f.initial_message;null!=a&&(b=f.initial_message_style,null==b&&(b="background-color:red;top:10px;left:10px;height:100px;width:200px"),b="z-index:99;position:absolute;"+b,zc=p("div"),zc.setAttribute("style",b),zc.innerHTML=a,zc.addEventListener("click",function(){zc.style.visibility="hidden"},!1),zc.style.visibility="visible",
Xa.appendChild(zc),b=f.initial_message_timeout,null!=b&&("auto"==b?Yf=!0:(Yf=!1,b=parseInt(f.initial_message_timeout,10),2>b&&(b=2),setTimeout(function(){zc.style.visibility="hidden"},1E3*b))));yd=null;a=f.initial_enhancement;null!=a&&(yd=parseInt(a,10)-1);zd=!1;Xe="X = ";Ye=" Y = ";a=f.coordinates;null!=a&&(D(a),zd=!0,Xe="Lat = ",Ye=" Lon = ");d="green";c="white";R="12px Arial";var P=null,l=g=10,k=10;Zf=2;a=f.keyboard_propagate;null!=a&&z(a,"t")&&(Ze=!1);a=f.coordinates_display_style;null!=a&&(b=
a.split(","),d=b[0].trim(),c=b[1].trim(),R=b[2].trim(),3<b.length&&(Xe=b[3],Ye=b[4],Zf=parseInt(b[5],10),6<b.length&&(P=b[6].trim(),g=parseInt(b[7],10),l=parseInt(b[8],10),k=parseInt(b[9],10))));qh=new ob(d,c,R,P,g,l,k);$e=Rc=null;null!=f.map_scale&&(af=bc=!0,b=f.map_scale.split(","),Rc=parseFloat(b[0]),$e=1<b.length?parseFloat(b[1]):Rc);Ad=zd?"km":" ";bf=1;a=f.distance_unit;null!=a&&(Ad=a.trim(),z(Ad,"mi")&&(bf=.621371192),z(Ad,"nm")&&(bf=.539956803),z(Ad,"na")&&(bf=.539956803));ne=null;a=f.show_bearing;
null!=a&&(ne=a.trim());a=f.divcan_style;null!=a&&a.trim();$f="default";a=f.distance_cursor;null!=a&&($f=a.trim());cf="default";a=f.location_cursor;null!=a&&(cf=a.trim());df="default";a=f.probe_cursor;null!=a&&(df=a.trim());ag="default";a=f.mark_cursor;null!=a&&(ag=a.trim());a=f.imagecan_style;null!=a&&(b=a.trim()+";position:absolute;top:0;left:0;",tb.setAttribute("style",b+"z-index:1;"),Ac.setAttribute("style",b+"z-index:12;"));d="blue";c="white";R="12px Arial";P=null;k=l=g=10;bg=1;rh="white";a=f.distance_display_style;
null!=a&&(b=a.split(","),d=b[0].trim(),c=b[1].trim(),rh=5<=b.length?b[4].trim():c,R=b[2].trim(),bg=parseInt(b[3],10),5<b.length&&(P=b[5].trim(),g=parseInt(b[6],10),l=parseInt(b[7],10),k=parseInt(b[8],10)));Oi=new ob(d,c,R,P,g,l,k);d="black";c="white";R="12px Arial";P=null;k=l=g=10;a=f.probe_display_style;null!=a&&(b=a.split(","),d=b[0].trim(),c=b[1].trim(),R=b[2].trim(),3<b.length&&(P=b[3].trim(),g=parseInt(b[4],10),l=parseInt(b[5],10),k=parseInt(b[6],10)));Pi=new ob(d,c,R,P,g,l,k);sh="Undefined";
th=!1;oe=0;a=f.probe_undefined;null!=a&&(b=a.split(","),sh=b[0].trim(),1<b.length&&(oe=parseInt(b[1],10)+1),2<b.length&&(th=!0));cg=!1;f.probe_base_image&&(cg=!0);a=f.active_probe;null!=a&&(cc=!0);a=f.pause;null!=a&&(uh=parseInt(a,10));a=f.auto_refresh;null!=a&&(dg=6E4*parseInt(a,10),Sc=setInterval("HAniS.reloadFOF();",dg),pe=!0);ef=!1;vh="#FFFFFF80";a=f.show_hotspots;null!=a&&(b=a.split(","),z(b[0],"t")&&(ef=!0),1<b.length&&(vh=b[1]));eg=!1;z(f.center_hotspots,"t")&&(eg=!0);Bd=!1;z(f.enable_smoothing,
"t")&&(Bd=!0);wh="low";a=f.smoothing_quality;null!=a&&(wh=a);ff=!0;z(f.check_image_size,"f")&&(ff=!1);xh=!1;a=f.sprites;if(null!=a){b=a.split(",");fg=new Image;gg=[];hg=[];dc=[];ec=[];if("row"==b[1].trim().toLowerCase())for(l=c=d=0,a=2;a<b.length;)for("row"==b[a].trim().toLowerCase()&&(d=0,c+=l,l=0,a+=1),g=parseInt(b[a],10),a+=1,R=parseInt(b[a],10),a+=1,P=parseInt(b[a],10),P>l&&(l=P),a+=1,k=0;k<g;k++)gg.push(d),hg.push(c),dc.push(R),ec.push(P),d+=R;else for(c=!1,a=1;a<b.length;)gg.push(parseInt(b[a],
10)),a+=1,hg.push(parseInt(b[a],10)),a+=1,a>=b.length?(d=0,c=!0):d=parseInt(b[a],10),0>d?(c=!0,dc.push(Math.abs(d)),a+=1,d=parseInt(b[a++],10),ec.push(Math.abs(d))):c?(dc.push(dc[dc.length-1]),ec.push(ec[ec.length-1])):(dc.push(parseInt(b[a],10)),a+=1,ec.push(parseInt(b[a],10)),a+=1);fg.onload=function(){xh=!0};fg.src=b[0]}a=f.overlay_labels;null!=a&&(fc=a.split(","));ig=null;a=f.auto_enhance_background;null!=a&&(ig=parseInt(a,10)-1);Tc=null;a=f.auto_enhance;if(null!=a)for(d=f.overlay_probe_table,
b=a.split(","),Tc=Array(b.length),a=0;a<b.length;a++)"x"==b[a].trim().toLowerCase()?Tc[a]=-1:Tc[a]=parseInt(b[a].trim(),10)-1,null==d&&(Bc[a]=Tc[a]);Uc=!1;ub=-1;a=f.overlay_enhance;null!=a&&(Uc=!0,ub=parseInt(a,10)-1);Cc=null;Cd=!0;a=f.overlay_allow_hoverzones;if(null!=a)for(b=a.split(","),Cc=Array(b.length),a=0;a<b.length;a++)if(Cc[a]=!0,z(b[a],"n")||z(b[a],"f"))Cc[a]=!1;W=aa=null;Vc=yh=!1;a=f.window_size;null!=a&&(b=a.split(","),"div"==b[0]?Vc=!0:(W=2*Math.floor(parseInt(b[0],10)/2),aa=2*Math.floor(parseInt(b[1],
10)/2)),yh=!0);jg=[];a=f.framenumber_index_values;null!=a&&(jg=a.split(","));Kb=[];a=f.use_for_all_frames;if(null!=a)for(b=a.split(","),a=0;a<b.length;a+=2)Kb[parseInt(b[a],10)]=parseInt(b[a+1],10)-1;qe=-1;a=f.skip_missing;null!=a&&(qe=parseInt(a,10));zh="#00000000";a=f.skip_missing_color;null!=a&&(zh=a);gf=null;a=f.overlay_spacer;if(null!=a)for(b=a.split(","),gf=Array(b.length),a=0;a<b.length;a++)gf[a]=parseInt(b[a],10);a=f.overlay_probe_table;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)"x"==
b[a].trim().toLowerCase()?Bc[a]=-1:Bc[a]=parseInt(b[a],10)-1;kg=[];a=f.overlay_ontop;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)kg[parseInt(b[a],10)-1]=!0;Wc=null;a=f.overlay_order;null==a&&(a=f.overlay_zorder);if(null!=a)for(b=a.split(","),Wc=Array(b.length),a=0;a<b.length;a++)Wc[parseInt(b[a],10)-1]=a;gc=null;a=f.overlay_links;if(null!=a)for(b=a.split(","),gc=Array(b.length),a=0;a<b.length;a++)gc[a]=parseInt(b[a],10);Ah=[];K=null;a=f.overlay_slice;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)Ah[parseInt(b[a],
10)-1]=!0;Bh=!0;z(f.slice_smoothing,"f")&&(Bh=!1);Dd=null;a=f.overlay_clear;if(null!=a)for(b=a.split(","),Dd=Array(b.length),a=0;a<b.length;a++)Dd[a]=b[a].trim().toLowerCase();Ch=!1;a=f.transparency;null!=a&&(b=a.split(","),1==b.length?Dh=Eh=Fh=parseInt(b[0],10):(Dh=parseInt(b[0],10),Eh=parseInt(b[1],10),Fh=parseInt(b[2],10)),Ch=!0);lg=!1;a=f.transparency_list;if(null!=a){b=a.split(",");Gh=[];for(a=0;a<b.length;a++)Gh[parseInt(b[a].trim(),10)-1]=!0;lg=!0}hf=null;a=f.overlay_transparent_amount;if(null!=
a)for(b=a.split(","),hf=Array(b.length),a=0;a<b.length;a++)hf[a]=parseFloat(b[a])/100;Xc=null;a=f.overlay_zoom;if(null!=fc&&null!=a)for(b=a.split(","),Xc=Array(b.length),a=0;a<b.length;a++)if(Xc[a]=1,z(b[a],"n")||z(b[a],"f"))Xc[a]=0;else if(z(b[a],"d")||z(b[a],"h"))Xc[a]=-1;vb=null;Hh=[];a=f.overlay_preserve_list;if(null!=fc&&null!=a)for(b=a.split(","),vb=Array(b.length),a=0;a<b.length;a++){vb[a]=!0;if(z(b[a],"n")||z(b[a],"f"))vb[a]=!1;if(z(b[a],"a")||z(b[a],"A"))Hh[a]=!0}la=null;if(null!=fc&&null!=
vb)for(b=f.overlay_preserve.replace(/&/g,",&,").split(","),d=f.overlay_preserve_position,null!=d&&(d=d.split(",")),c=0,la=Array(vb.length),a=R=0;a<vb.length;a++)if(vb[a]){la[a]=[];P=0;do{la[a][P]=[];for(g=0;4>g;g++)la[a][P][g]=parseInt(b[R].trim(),10),R+=1;la[a][P][2]=la[a][P][2]-la[a][P][0]+1;la[a][P][3]=la[a][P][3]-la[a][P][1]+1;null!=d?(la[a][P][4]=parseInt(d[c],10),la[a][P][5]=parseInt(d[c+1],10),c+=2):(la[a][P][4]=la[a][P][0],la[a][P][5]=la[a][P][1]);R<b.length&&"&"==b[R].trim()?(R+=1,P+=1,g=
!0):g=!1}while(g)}jf=0;Ih=" ";Dc="white";re="transparent";se="14pt arial";Jh=!1;a=f.times_label_style;null!=a&&(b=a.split(","),Dc=b[0].trim(),1<b.length&&(jf=Math.floor(60*parseFloat(b[1]))),1<b.length&&(jf="?"==b[1].trim()||"auto"==b[1].trim().toLowerCase()?-Math.floor((new Date).getTimezoneOffset()):Math.floor(60*parseFloat(b[1]))),2<b.length&&(Ih=b[2].trim()),3<b.length&&(re=b[3].trim()),4<b.length&&(se=b[4].trim()),5<b.length&&-1!=b[5].trim().indexOf("t")&&(Jh=!0));0==Dc.indexOf("0x")&&(Dc="#"+
Dc.substring(2));0==re.indexOf("0x")&&(re="#"+re.substring(2));Ed=parseInt(se,10);Qi=new ob("black","white",se,"black",20,5,5);Kh=!1;Kh=z(f.to_from_lock,"t")?!0:!1;a="black";g="white";l="14px arial";d=null;P=R=c=10;Lh=Mh=" ";mg=Fd=null;a=f.dirspd_display_style;null!=a&&(b=a.split(","),a=b[0].trim(),g=b[1].trim(),l=b[2].trim(),Lh=b[3],Mh=b[4],5<b.length&&(d=b[5].trim(),c=parseInt(b[6],10),R=parseInt(b[7],10),P=parseInt(b[8],10)),mg=new ob(a,g,l,d,c,R,P));d="black";c="white";R="14px arial";P=null;k=
l=g=10;a=f.tipbox_display_style;null!=a&&(b=a.split(","),d=b[0].trim(),c=b[1].trim(),R=b[2].trim(),3<b.length&&(P=b[3].trim(),g=parseInt(b[4],10),l=parseInt(b[5],10),k=parseInt(b[6],10)));Nh=new ob(d,c,R,P,g,l,k);Gd=null;ia=f.image_base;null!=ia?Gd=ia=ia.trim():ia=null!=f.image_only_base?f.image_only_base.trim():null;Oh=ia;a=f.overlay_base;null!=a&&(wb=a.trim());kf=!0;z(f.zip_only,"f")&&(kf=!1);Yc=!1;a=f.zip_filename;null!=a&&(Yc=!0,ng=a.trim());xd=!0;a=f.filenames;null==a&&(a=f.background_filenames);
null!=a&&Ri(a);a=f.basename;null!=a&&(d=f.base_starting_number,c=0,R=1,null!=d&&(b=d.split(","),c=parseInt(b[0],10),1<b.length&&(R=parseInt(b[1],10))),t=f.num_frames,null==t&&(t=f.num_images),t=parseInt(t,10),Si(a,c,R));og=!0;b=f.zip_static;if(z(b,"f")||z(b,"n"))og=!1;pg=!0;b=f.background_static;if(z(b,"f")||z(b,"n"))pg=!1;a=f.overlay_filenames;null!=a&&Ti(a);Qa=null;a=f.image_preserve;if(null!=a)for(b=a.split(","),Qa=[],a=0;a<b.length;a++)Qa[a]=parseInt(b[a].trim(),10),1<a%4&&(Qa[a]=Qa[a]-Qa[a-2]+
1);Ph=!1;z(f.keep_enhancement,"t")&&(Ph=!0);Qh=!0;z(f.keep_zoom,"f")&&(Qh=!1);Hd=qg=0;Rh=!1;a=f.hide_bottom;null!=a&&(b=a.split(","),qg=parseInt(b[0].trim(),10),1<b.length&&z(b[1],"t")&&(Rh=!0));Id=rg=0;Sh=!1;a=f.hide_top;null!=a&&(b=a.split(","),rg=parseInt(b[0].trim(),10),1<b.length&&z(b[1],"t")&&(Sh=!0));Jd=sg=0;Th=!1;a=f.hide_left;null!=a&&(b=a.split(","),sg=parseInt(b[0].trim(),10),1<b.length&&z(b[1],"t")&&(Th=!0));Kd=tg=0;Uh=!1;a=f.hide_right;null!=a&&(b=a.split(","),tg=parseInt(b[0].trim(),
10),1<b.length&&z(b[1],"t")&&(Uh=!0));Vh=!1;z(f.hide_background,"t")&&(Vh=!0);Wh="<div>";Xh=300;Yh=500;a=f.popup_style;null!=a&&(Wh='<div style="'+a+'">');a=f.popup_window_size;null!=a&&(b=a.split(","),Yh=b[0],Xh=b[1]);Zh=!1;a=f.wheel_frames;null!=a&&(Zh=!0,pa.useWheel(G.wheel));$h=Ia=!1;z(f.active_zoom,"t")&&(null==La&&(Ia=!0),pa.useWheel(G.wheel));ug=!1;z(f.cycle_zoom,"t")&&(ug=!0);a=f.initial_zoom;null!=a&&(b=a.split(","),Ec="auto"!=b[0].toLowerCase()?parseFloat(b[0]):"auto",1<b.length?(te=parseInt(b[1],
10),ai=parseInt(b[2],10)):te=-1,bi=!0);Ld=1;Md=!1;sa=null;a=f.zoom_scale;if(null!=a)if(b=a.split(","),1===b.length)z(a,"hi_res")?(Md=!0,Ld=0):Ld=parseFloat(a);else{sa=Array(b.length);for(a=0;a<b.length;a++)sa[a]=parseFloat(b[a]);Md=!0}Zc=9999999;a=f.maximum_zoom;null!=a&&(Zc=parseFloat(a));lf=!0;z(f.use_progress_bar,"f")&&(lf=!1);a=f.dwell;null!=a&&(b=a.split(","),Ja=parseInt(b[0].trim(),10),1<b.length&&(hc=parseInt(b[1].trim(),10),10>hc&&(hc=10),$c=parseInt(b[2].trim(),10),vg=parseInt(b[3].trim(),
10)));a=f.rate;null!=a&&(b=a.split(","),Ja=Math.round(1E4/parseFloat(b[0].trim())),1<b.length&&(hc=Math.round(1E4/parseFloat(b[2].trim())),10>hc&&(hc=10),$c=Math.round(1E4/parseFloat(b[1].trim()))));a=f.frame_times_template;null!=a&&(b=a.split(","));Nd=27;a=f.mp4_quantization;null!=a&&(Nd=parseInt(a,10),10>Nd||51<Nd)&&(Nd=27);xb=null;a=f.times;if(null!=a){b=a.split(",");xb=Array(b.length);for(a=0;a<b.length;a++)xb[a]=parseInt(b[a].trim(),10);Z(xb)}a=f.extrap_times_filename;if(null!=a){xb=[];var h=
new XMLHttpRequest;h.open("get",a,!0);h.onload=function(){for(var a=h.responseText.split("\n"),b=0;b<a.length;b++){var d=a[b].split(" ");if(3==d.length){d[2].trim();var g=parseInt(d[0],10)-1;xb[g]=100*parseInt(d[2].substring(0,2),10)+parseInt(d[2].substring(3,5),10)+parseInt(d[2].substring(6,8),10)/30}}Z(xb)};h.send()}ue=null;a=f.extrap_times_template;null!=a&&(ue=RegExp(a));ci=["Click on target's initial position","Click on target's final position","Move pointer around or click here to select target"];
di=10;z(f.extrap_prompts_position,"bot")&&(di=9999);a=f.extrap_prompts;null!=a&&(ci=a.split(","));mf=["Click on first point to mark","Save points","Remove last point"];a=f.mark_prompts;null!=a&&(mf=a.split(","));nf=!0;z(f.mark_close,"f")&&(nf=!1);wg="12pt Arial";ei="white";a=f.mark_prompts_style;null!=a&&(b=a.split(","),wg=b[0].trim(),1<b.length&&(ei=b[1].trim()));fi=f.controls;ha("controls = "+f.controls);ha("bottom_controls = "+f.bottom_controls);ad=of=ic=jc=yb=zb=pf=Lb=null;null!=fi&&mb(fi,!0);
gi=f.bottom_controls;null!=gi&&mb(gi,!1);bd=!1;a=f.probe_table;null!=a&&q(a);b=f.enhance_filename;null==b&&(b=f.enhance_table);if(null!=b){ha("Reading enhancement table...");bd=!1;h=new XMLHttpRequest;Ab=[];cd=[];qf=[];dd=[];kc=[];var S,Fc,m;cb=[];db=[];eb=[];ve=[];v=-1;hi=!0;var xg=!1,r,A,y,n,E,x,H,Q,F,B,J,I,C;h.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var d=a[b].replace(/\s+/g," ").trim(),g=d.indexOf("#");if(0!=g)if(0<g&&(d=d.substring(0,
g)),g=d.split(","),0==g[0].indexOf("*"))v++,Ab[v]=Array(256),dd[v]=Array(256),cd[v]=Array(256),kc[v]=Array(256),cb[v]=Array(256),db[v]=Array(256),eb[v]=Array(256),ve[v]=Array(256),Ab[v]=Array(256),qf[v]=1<g.length?g[1].trim():"None",S=" ",Fc="Value =",m=1,d=p("option"),d.innerHTML=g[0].substring(1),d.value=v,null!=Fa&&Fa.add(d);else{var c=d.indexOf("value");0>c&&(c=d.indexOf("probe"));xg=!1;B=J=0;0<c&&(g=d.substring(c+1),d=d.substring(0,c),c=g.indexOf("="),g=g.substring(c+1),g=g.split(","),1==g.length?
(Fc=g[0].trim(),m=-1,xg=!1):(B=parseFloat(g[0].trim()),J=parseFloat(g[1].trim()),2<g.length&&(m=parseInt(g[2],10)),3<g.length&&(S=Ui(g[3].trim())),4<g.length&&(Fc=g[4].trim()),xg=!0));d=d.split(" ");r=parseInt(d[0].trim(),10);A=parseInt(d[1].trim(),10);y=A-r;n=parseFloat(d[2].trim());E=parseFloat(d[3].trim());x=parseFloat(d[4].trim());H=parseFloat(d[5].trim());Q=parseFloat(d[6].trim());F=parseFloat(d[7].trim());I=C=255;9<d.length&&(I=parseFloat(d[8].trim()),C=parseFloat(d[9].trim()));for(d=r;d<=A;d++)0===
y?(cb[v][r]=n,db[v][r]=x,eb[v][r]=Q,ve[v][r]=I):(cb[v][d]=Math.round(n+(E-n)*(d-r)/y),db[v][d]=Math.round(x+(H-x)*(d-r)/y),eb[v][d]=Math.round(Q+(F-Q)*(d-r)/y),ve[v][d]=Math.round(I+(C-I)*(d-r)/y)),dd[v][d]=Fc,cd[v][d]=S,kc[v][d]=m,xg&&(Ab[v][d]=B+(J-B)*(d-r)/y)}}-1!=ub&&w[ub].checked&&(Fa.disabled=!1);bd=!0;e()};h.open("get",b,!0);h.send()}else e()}function e(){var b=f.sprite_filenames;if(null!=b){var a=b.split(",");yg=0;qa=[];b=f.sprite_images_offset;ed=-1;null!=b&&(ed=parseInt(b,10)-1);for(b=0;b<
a.length;b++){qa[b]=new Image;qa[b].gotit=!1;qa[b].inx=b;qa[b].fromfile=!0;var g="/";0<a[b].indexOf("?")&&(g="?");qa[b].zoomme=0<a[b].indexOf(g+"zoom");qa[b].anim=0<a[b].indexOf(g+"animate");g=a[b].indexOf(g);0<g&&(a[b]=a[b].substring(0,g));qa[b].onload=function(){qa[this.inx].gotit=!0;yg++;yg==a.length&&h()};qa[b].src=a[b].trim()}}else h()}function h(){for(var b=Object.keys(f),a=0;a<b.length;a++)z(b[a],"hotspot")&&Yb("hotspot="+f[b[a]]);xd?G.getFOF():(Gc=!0,Xb())}function q(b){var a=new XMLHttpRequest;
Ab=[];qf=[];cd=[];var g=" ";dd=[];var d="Value=";kc=[];var c=1;fd=[];zg=[];cb=[];db=[];eb=[];var f,e=-1;v=-1;var l=0;a.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var ma=a[b].replace(/\s+/g," ").trim().split(","),R=ma[0].split(" ");if(0==R[0].indexOf("*"))v++,Ab[v]=[],dd[v]=[],cd[v]=[],kc[v]=[],cb[v]=[],db[v]=[],eb[v]=[],zg[v]=[],fd[v]=[],e=-1,qf[v]=1<ma.length?ma[1].trim():"None",l=1;else if(0!=l){e++;var k=Array(3);Ab[v][e]=parseFloat(R[0]);
cb[v][e]=parseInt(R[1].trim(),10);db[v][e]=parseInt(R[2].trim(),10);eb[v][e]=parseInt(R[3].trim(),10);0!=e&&(k[0]=cb[v][e]-cb[v][e-1],k[1]=db[v][e]-db[v][e-1],k[2]=eb[v][e]-eb[v][e-1],f=0,Math.abs(k[1])>Math.abs(k[f])&&(f=1),Math.abs(k[2])>Math.abs(k[f])&&(f=2),zg[v][e-1]=f,fd[v][e-1]=k,0==fd[v][e-1][f]&&(fd[v][e-1][f]=1));1<ma.length&&(0==ma[1].trim().indexOf('"')?(c=-1,ma=ma[1].trim(),d=ma.substr(1,ma.length-2),g=""):(c=parseInt(ma[1],10),2<ma.length&&(g=Ui(ma[2].trim())),3<ma.length&&(d=ma[3].trim())));
dd[v][e]=d;kc[v][e]=c;cd[v][e]=g}}bd=!0};a.open("get",b,!0);a.send()}function D(b){b=b.split(",");var a=b[0].trim();"PS"===a?(lc=new nj,lc.init(b)):"CE"==a?(lc=new oj,lc.init(b)):"LCC"==a?(lc=new pj,lc.init(b)):(lc=null,Ag=parseFloat(b[0]),Bg=parseFloat(b[1]),Vi=parseFloat(b[2]),Cg=parseFloat(b[3]),0<Bg&&0>Cg&&(Cg+=360));null==f.coordinates_display_style&&(Xe="Lat = ",Ye=" Lon = ");zd=!0}function Hb(b){var a=new XMLHttpRequest;a.onload=function(){c(this.responseText.split("\n"))};a.open("get",b+"?"+
Math.round(1E5*Math.random()),!0);a.send()}function xc(b){var a;if(null!=Dd){for(a=0;a<Dd.length;a++)-1!=Dd[a].indexOf(b)&&(w[a].checked=!1);for(a=0;a<Dd.length;a++)Jb(a)}}function Z(b){Dg=Array(b.length);for(var a=0;a<b.length;a++){var g=60*Math.floor(b[a]/100)+Math.floor(b[a])%100;0===a&&(mc=g);var d=g-mc;0>d&&(d=g+1440-mc);Dg[a]=d;ha("times s="+g+"  min="+Dg[a])}mc+=jf;1440<=mc&&(mc-=1440);0>mc&&(mc+=1440);ha("Starting minute = "+mc)}function lb(b,a){if(0!=b&&!gd)for(var g=0;g<b;g++)0==w[Ra[g].overlay].isGhost&&
(w[Ra[g].overlay].parentNode.style.visibility=a)}function na(){var b,a,g,d,c;if(Eg){var f=new XMLHttpRequest;var e=0;T=[];f.onload=function(){var ma=this.responseText.split("\n");ha("Processing FoF-substitute: "+ii);for(g=0;g<ma.length;g++)if(!(2>ma[g].length||0>ma[g].indexOf(Wi))&&(T[e]=[],c=ma[g].indexOf("overlay"),0<=c)){b=ma[g].substring(c);c=b.indexOf("=");0>c&&ha("!! Cannot find a = sign in "+b);a=b.substring(c+1);b=a.trim();a=b.split(",");X=Math.max(X,a.length);ha("numOverlays reset in fof_substitute to "+
X);for(d=0;d<a.length;d++)T[e][d]=a[d].trim(),null!=we&&Fg[d]?T[e][d]=(we+T[e][d]).trim():null!=wb?T[e][d]=(wb+T[e][d]).trim():null!=ia&&(T[e][d]=(ia+T[e][d]).trim());e+=1}ha("Number of frames "+t+"... number of fof_sub frames = "+e);Te()};f.open("get",ii+"?"+Math.round(1E5*Math.random()),!0);f.send()}else Te()}function Te(){0!=Bb?lb(Bb,"visible"):0!=ji&&lb(ji,"hidden");Gc=!0;Xb()}function vd(b,a){Od||(tb.height=a,tb.width=b,Ac.height=a,Ac.width=b,xe.height=a,xe.width=b,Pd.height=a,Pd.width=b,ye=
Pd.getContext("2d"),W=2*Math.floor(b/2),aa=2*Math.floor(a/2),Vc&&(b=Qd*aa/W,a=Qd,b<hd&&(a=hd*W/aa,b=hd),ta=a,ua=b),rf=W/2-100,sf=aa/2-10,H=ta/W,F=ua/aa,za=Math.floor(ta/B),Aa=Math.floor(ua/J),Hc=Ic=0,Vc&&(Ic=Math.round((ta-Qd)/2),Hc=Math.round((ua-hd)/2)),Xa.style.height=aa+"px",Xa.style.width=W+"px",Jc.style.height=aa+"px",Jc.style.width=W+"px",ze.style.height=aa+"px",ze.style.width=W+"px",Ue(t,!1),ki&&(ki=!1,null!=Ae&&Ae()))}function Wf(){for(var b=0,a={},g=0;g<t;a={$jscomp$loop$prop$ii$2:a.$jscomp$loop$prop$ii$2},
g++){a.$jscomp$loop$prop$ii$2=g;var d=null==ia?Ba[g]:Ba[g].substring(Ba[g].lastIndexOf("/")+1);(d=li.file(d))?d.async("arraybuffer").then(function(a){return function(d){d=new Blob([d]);Kc[a.$jscomp$loop$prop$ii$2]=URL.createObjectURL(d);b++;b>=t&&Oa()}}(a),function(a){return function(){Kc[a.$jscomp$loop$prop$ii$2]=null;b++;b>=t&&Oa()}}(a)):(Kc[a.$jscomp$loop$prop$ii$2]=null,b++,b>=t&&Oa())}}function Oa(){var b=0;if(0==X)Ib();else for(var a=0;a<t;a++){Lc[a]=[];for(var g={},d=0;d<X;g={$jscomp$loop$prop$ii$6:g.$jscomp$loop$prop$ii$6,
$jscomp$loop$prop$jj$7:g.$jscomp$loop$prop$jj$7},d++){g.$jscomp$loop$prop$ii$6=a;g.$jscomp$loop$prop$jj$7=d;var c=null==wb&&null==ia?T[a][d]:T[a][d].substring(T[a][d].lastIndexOf("/")+1);(c=li.file(c))?c.async("arraybuffer").then(function(a){return function(d){d=new Blob([d]);Lc[a.$jscomp$loop$prop$ii$6][a.$jscomp$loop$prop$jj$7]=URL.createObjectURL(d);b++;b>=t*X&&Ib()}}(g),function(a){return function(){Lc[a.$jscomp$loop$prop$ii$6][a.$jscomp$loop$prop$jj$7]=null;b++;b>=t*X&&Ib()}}(g)):(Lc[a][d]=null,
b++,b>=t*X&&Ib())}}}function Xb(){if(Yc){var b=new XMLHttpRequest,a=null==Gd?ng:Gd+ng;og||(a=a+"?"+Math.round(1E5*Math.random()));b.open("GET",a,!0);b.responseType="arraybuffer";Kc=[];Lc=[];b.addEventListener("progress",function(a){a.lengthComputable&&ya("Loading ZIP file",a.total,a.loaded)});b.onload=function(a){(new JSZip).loadAsync(this.response).then(function(a){li=a;Wf()},function(){ha("Unable to read ZIP file: "+ng)})};b.send()}else Ib()}function Ib(){var b,a,g;void 0!=tf&&tf(!1);var d="?"+
Math.round(1E4*Math.random()),c=[];c[0]=Mb;null!=Cb&&(Cb.disabled=!0);null!=Nb&&(Nb.disabled=!0);for(b=1;b<t;b++)c[b]=b<=Mb?b-1:b;Sa=Array(t);nc=Ta=0;mi=lf;Gg&&(Ma.max=t);Od&&(Rd||Uc)&&(oc=[],Ya=[],id=[],Hg=[],uf=[]);null!=Fa&&(Ph?null==yd&&(yd=Fa.value):Fa.selectedIndex=0);for(var f=0;f<t;f++){b=c[f];Od&&(Rd||Uc)&&(oc[b]=p("canvas"),Ya[b]=p("canvas"));Sa[b]=new Image;Sa[b].gotit=!1;Sa[b].frameNum=b;Sa[b].onerror=function(){Ta++};Sa[b].onload=function(){Od&&(ua=this.height,ta=this.width,hd=ua,Qd=
ta,Od=!1,yh?Vc?G.setWindowSize(u.offsetWidth,u.offsetHeight):vd(W,aa):vd(ta,ua),Aa=ua,za=ta,bi&&("auto"==Ec&&(Ec=(H+F)/2,te=-1),Aa/=Ec,za/=Ec,0>te&&(te=ta/2,ai=ua/2),N=Math.round(te-ta/2/Ec),O=Math.round(ai-ua/2/Ec),B=J=Ec,1!=Ec&&(Ia=!1,G.toggleZooming()),Hd=qg,Id=rg,Kd=tg,Jd=sg,Pc()));Yc&&null!=Kc[this.frameNum]&&URL.revokeObjectURL(Kc[this.frameNum]);if(0<vf&&!Sd){Ig.height=ua;Ig.width=ta;Be=Ig.getContext("2d");Be.clearRect(0,0,W,aa);for(var b=0;b<Za.length;b++){for(var f=Za[b].ctx.getImageData(0,
0,Za[b].width,Za[b].height).data,ma=Be.getImageData(Za[b].xmin,Za[b].ymin,Za[b].width,Za[b].height),e=3;e<f.length;e+=4)0!=f[e]&&(ma.data[e]=b+1);Be.putImageData(ma,Za[b].xmin,Za[b].ymin)}Ia||(qb=!0);B==wf&&(qb=!0);Sd=!0}if(Gc){Gc=!1;C=tb.getContext("2d");C.imageSmoothingEnabled=Bd;C.imageSmoothingQuality=wh;C.fillStyle="blue";C.font="bold 20px Arial";k=Ac.getContext("2d");k.imageSmoothingEnabled=Bd;$a=Array(t);Ue(t,!0);xf&&!Ca?xa(oa(Mb)):xa(oa(m));if(0<X)for(L=Array(t),e=0;e<t;e++)for(g=c[e],L[g]=
Array(X),a=0;a<X;a++)if(void 0!=Kb[a+1]&&Kb[a+1]>=t&&(Kb[a+1]=t-1),void 0==Kb[a+1]||Kb[a+1]==g)L[g][a]=new Image,L[g][a].gotit=!1,L[g][a].frameNum=g,L[g][a].overlayNum=a,L[g][a].onerror=function(){Ta++},L[g][a].onload=function(){this.gotit=!0;var a=this.frameNum;Ta++;Qc();!ff||this.height==hd&&this.width==Qd?this.overlayNum==qe-1&&($a[this.frameNum]=0):(this.gotit=!1,ha("Bad image size:"+this.src));if(Uc&&this.gotit&&this.overlayNum==ub)oc[a].height=this.height,oc[a].width=this.width,Ce=oc[a].getContext("2d"),
Ce.drawImage(this,0,0),Hg[a]=Ce.getImageData(0,0,this.width,this.height).data,Ya[a].height=this.height,Ya[a].width=this.width,id[a]=Ya[a].getContext("2d"),id[a].drawImage(this,0,0),uf[a]=id[a].getImageData(0,0,this.width,this.height),L[a][this.overlayNum]=null,L[a][this.overlayNum]=Ya[a],L[a][this.overlayNum].gotit=!0;else if(this.gotit&&w[this.overlayNum].hotspotIndex){var b=p("canvas");b.height=this.height;b.width=this.width;var d=b.getContext("2d");d.drawImage(this,0,0);var g=d.getImageData(0,
0,this.width,this.height).data,c=g.length;var e=this.overlayNum;var f;for(f=0;f<c;f+=4)if(0!=g[f]){0==fb&&(gb=[]);var ma=g[f];var l=Math.floor(f/4/b.width);d=Math.floor(f/4%b.width);gb[fb]=new nb(d,l,"spritefn",ma,"pan",null,null,e,a,null,null);fb++}}else if(this.gotit&&Ch&&(!lg||lg&&Gh[this.overlayNum])){b=p("canvas");b.height=this.height;b.width=this.width;d=b.getContext("2d");d.drawImage(this,0,0);l=d.getImageData(0,0,this.width,this.height);g=l.data;c=g.length;for(f=0;f<c;f+=4)g[f]===Dh&&g[f+
1]===Eh&&g[f+2]===Fh&&(g[f+3]=0);d.putImageData(l,0,0);L[a][this.overlayNum]=null;L[a][this.overlayNum]=b;L[a][this.overlayNum].gotit=!0}this.gotit&&kg[this.overlayNum]?(Jg.clearRect(0,0,W,aa),Jg.drawImage(L[a][this.overlayNum],0,0,W,aa)):this.gotit&&Ah[this.overlayNum]&&null!=K&&(b=p("canvas"),b.height=ua,b.width=ta,8>K.length&&(K[4]=0,K[5]=0,K[6]=ta,K[7]=ua),d=b.getContext("2d"),d.imageSmoothingEnabled=Bh,d.drawImage(this,K[0],K[1],K[2],K[3],K[4],K[5],K[6],K[7]),L[a][this.overlayNum]=null,L[a][this.overlayNum]=
b,L[a][this.overlayNum].gotit=!0,null!=vb&&vb[this.overlayNum]&&(L[a][this.overlayNum].origImage=this));Yc&&null!=Lc[a][this.overlayNum]&&URL.revokeObjectURL(Lc[a][this.overlayNum]);if(void 0!=Kb[this.overlayNum+1]&&Kb[this.overlayNum+1]==a)for(b=0;b<t;b++)b!=a&&(L[b][this.overlayNum]=L[a][this.overlayNum],Ta++)},b=T[g][a],void 0==De||De[a]||(b+=d),L[g][a].src=Yc&&(kf||Lc[g][a])?Lc[g][a]:b,nc++;if(null!=jd)for(pc=[],a=0;a<jd.length;a++)pc[a]=new Image,pc[a].gotit=!1,pc[a].onerror=function(a){Ta++},
pc[a].onload=function(a){a.currentTarget.gotit=!0;Ta++;Qc()},pc[a].src=jd[a],nc++;if(null!=Ua&&0<Ua.length)for(Da=[],a=0;a<Ua.length;a++)if(void 0!=Ua[a])for(Da[a]=[],g=0;g<Ua[a].length;g++)for(Da[a][g]=[],e=0;e<t;e++)Xi(Ua[a][g],"/")?(b=T[e][a].lastIndexOf("/"),b=T[e][a].substring(0,b+1)+Ua[a][g]+T[e][a].substring(b+1),Da[a][g][e]=new Image,Da[a][g][e].gotit=!1,Da[a][g][e].onerror=function(a){Ta++;Qc()},Da[a][g][e].onload=function(a){a.currentTarget.gotit=!0;Ta++;Qc()},Da[a][g][e].src=b,nc++):0===
e?(Da[a][g][0]=new Image,Da[a][g][0].gotit=!1,Da[a][g][0].onerror=function(a){Ta++;Qc()},Da[a][g][0].onload=function(a){a.currentTarget.gotit=!0;Ta++;Qc()},Da[a][g][0].src=Ua[a][g],nc++):Da[a][g][e]=Da[a][g][0]}!ff&&0!=this.height&&0!=this.width||this.height==hd&&this.width==Qd?(this.gotit=!0,0==qe&&($a[this.frameNum]=0)):(this.gotit=!1,ha("Image has invalid size:"+this.src));Rd&&this.gotit&&(e=this.frameNum,oc[e].height=this.height,oc[e].width=this.width,Ce=oc[e].getContext("2d"),Ce.drawImage(this,
0,0),Hg[e]=Ce.getImageData(0,0,this.width,this.height).data,Ya[e].height=this.height,Ya[e].width=this.width,id[e]=Ya[e].getContext("2d"),id[e].drawImage(this,0,0),uf[e]=id[e].getImageData(0,0,this.width,this.height),Sa[e]=null,Sa[e]=Ya[e],Sa[e].gotit=!0);Ta++;Qc();Qh||G.resetZoom();kd=!0;Yi||(Yi=!0,Ga=!1,Zi());E(Ca)};var e=Ba[b];void 0!=Kb[0]&&(e=Kb[0],e>=t&&(e=t-1),e=Ba[e]);pg||(e+=d);Sa[b].src=Yc&&(kf||Kc[b])?Kc[b]:e;nc++}ld=Ob=!1;fa()}function ea(b,a,g,d,c,e){b.label_on=g;b.label_off=d;pb&&(b.className=
e);g=null;d=f[a+"_labels"];null==d&&(d=f[a+"_label"]);null!=d&&(d=d.split(","),b.label_on=d[0].trim(),1<d.length&&(b.label_off=d[1].trim()),2<d.length&&(g="width:"+d[2].trim()+"px;"));null!=c&&(b.title=c);b.innerHTML=b.label_on;c=a=d=f[a+"_style"];null!=d&&(d=d.split("&"),1<d.length&&(a=d[0],c=d[1]));b.style_on=(null!=g?g:"")+Mc+a;b.style_off=(null!=g?g:"")+Mc+c;null!=b.style_on&&1<b.style_on.length?b.setAttribute("style",b.style_on):(b.style_on=null,b.style_off=null)}function mb(b,a){Mc=f.buttons_style;
null==Mc&&(Mc="");var g=null,d=null;g=a?f.controls_tooltip:f.bottom_controls_tooltip;var c=b.split(",");if(null!=g){var e=g.split(",");e.length!=c.length&&(ha("!!! Number of tooltips must equal number of controls!"),e=g=null)}var k={};for(b=0;b<c.length;k={$jscomp$loop$prop$sfbounds$11:k.$jscomp$loop$prop$sfbounds$11},b++){var l=null!=g?e[b]:null;var h=c[b].trim();d=h.indexOf("/");if(0===d||0===b){0===d&&(h=h.substring(1));y=p("div");y.align=me;var q=f.controls_style;null!=q?y.setAttribute("style",
q):y.setAttribute("style","position:relative;padding:2px;width:100%;");a?(u.insertBefore(y,Xa),yf=y,yf.id=zf+"-top-controls"):(q=f.bottom_controls_style,null!=q&&y.setAttribute("style",q),u.appendChild(y),Af=y,Af.id=zf+"-bottom-controls")}"enhance"==h.trim()&&(Fa=p("select"),d=f.enhance_style,null!=d&&Fa.setAttribute("style",d),null!=l&&(Fa.title=l),d=p("option"),d.innerHTML=void 0==f.enhance_prompt?"Pick Enhancement":f.enhance_prompt,d.value=-1,Fa.add(d),Fa.addEventListener("change",G.doEnhance,
!1),Rd=!Uc,Fa.disabled=Rd?!1:!0,y.appendChild(Fa));"custom"==h&&(pf=p("button"),ea(pf,"custom","On","Off",l,"custom"),y.appendChild(pf));"mp4"==h&&(Nb=p("button"),ea(Nb,"mp4","Make MP4","Stop",l,"mp4"),Nb.addEventListener("click",G.makeMP4,!1),y.appendChild(Nb));"anigif"==h&&(Cb=p("button"),ea(Cb,"anigif","Make GIF","Stop",l,"anigif"),Cb.addEventListener("click",G.makeAniGIF,!1),y.appendChild(Cb));"startstop"==h&&(Lb=p("button"),ea(Lb,"startstop","Start","Stop",l,"startstop start"),Lb.addEventListener("click",
G.toggleIsLooping,!1),y.appendChild(Lb));"looprock"==h&&(Ee=p("button"),ea(Ee,"looprock","Rock","Loop",l,"looprock rock"),Fe=1,Ee.addEventListener("click",G.toggleLoopRock,!1),y.appendChild(Ee),z(f.start_rocking,"t")&&G.toggleLoopRock());"loophalt"==h&&(Ge=p("button"),ea(Ge,"loophalt","Halt","Loop",l,"loophalt halt"),Db=!1,Ge.addEventListener("click",G.toggleLoopHalt,!1),y.appendChild(Ge));"extrap"==h&&(qc=p("button"),ea(qc,"extrap","Enable Extrap","Disable Extrap",l,"extrap"),qc.addEventListener("click",
G.toggleExtrap,!1),y.appendChild(qc));z(h,"location")&&(Td=p("button"),ea(Td,"location","Show Loc","Hide Loc",l,"location"),0<h.indexOf("/on")?(I(Td,!1,"location off"),Ud=!0,Na.push(u.style.cursor),u.style.cursor=cf):(Ud=!1,u.style.cursor=Na.pop()),Td.addEventListener("click",function(){(Ud=!Ud)?(I(Td,!1,"location off"),Na.push(u.style.cursor),u.style.cursor=cf):(I(Td,!0,"location on"),u.style.cursor=Na.pop());fa()},!1),y.appendChild(Td));"distance"==h&&(rc=p("button"),ea(rc,"distance","Show dist",
"Hide dist",l,"distance"),bc=af=!1,rc.addEventListener("click",function(){(bc=!bc)?(I(rc,!1,"distance off"),Na.push(u.style.cursor),u.style.cursor=$f):(I(rc,!0,"distance on"),u.style.cursor=Na.pop())},!1),y.appendChild(rc));z(h,"probe")&&(Vd=p("button"),ea(Vd,"probe","Show probe","Hide probe",l,"probe"),0<h.indexOf("/on")?(I(Vd,!1,"probe off"),cc=!0,Na.push(u.style.cursor),u.style.cursor=df):(cc=!1,u.style.cursor=Na.pop()),Vd.addEventListener("click",function(){(cc=!cc)?(I(Vd,!1,"probe off"),Na.push(u.style.cursor),
u.style.cursor=df):(I(Vd,!0,"probe on"),u.style.cursor=Na.pop())},!1),y.appendChild(Vd));"mark"==h&&(md=p("button"),ea(md,"mark","Mark","Stop Mark",l,"mark"),He=!0,md.addEventListener("click",function(){Eb=!Eb;va=[];Eb?(Wd=0,I(md,!1,"mark off"),null!=La&&(La.disabled=!0),Na.push(u.style.cursor),u.style.cursor=ag):(I(md,!0,"mark on"),null!=La&&(La.disabled=!1),Wd=-1,u.style.cursor=Na.pop());fa()},!1),$i=new ob("black","white",wg,"black",20,5,5),ni=new ob("black","white",wg,"black",20,5,5),y.appendChild(md));
"refresh"==h&&(of=p("button"),ea(of,"refresh","Refresh",null,l,"refresh"),of.addEventListener("click",G.reloadFOF,!1),y.appendChild(of));"restore"==h&&(Kg=p("button"),ea(Kg,"restore","Restore",null,l,"restore"),Kg.addEventListener("click",function(a){for(a=0;a<w.length;a++)w[a].checked=w[a].restorableState;for(a=0;a<w.length;a++)Jb(a)},!1),y.appendChild(Kg));"setframe"==h&&(k.$jscomp$loop$prop$sfbounds$11=function(){var a=parseInt(Ma.value,10)-1;if(Bf||Lg){for(var b=0;b<t;b++)Ka(b,0);Cf=0}else if(a!=
oi&&Mg){if(0==Cf){for(b=0;b<t;b++)b>a?Ka(b,0):Ka(b,-1);Cf=1}else{for(b=a+1;b<t;b++)Ka(b,-1);Cf=0;E(!0)}oi=a}},Ma=p("input"),pb&&(Ma.className="setframe"),Ma.type="range",Ma.min=1,Ma.max=100,Ma.value=1,Df="Frame #*",null!=l&&(Ma.title=l),q=f.setframe_label,null!=q&&(Df=q),Ie=p("span"),Ie.innerHTML=Df.replace("*",1),d="display:block;vertical-align:middle;"+f.setframe_style,Ma.setAttribute("style",d),d=p("span"),d.setAttribute("style","display:inline-block;vertical-align:top;"),Ie.setAttribute("style",
"display:block;vertical-align:middle;"+f.setframe_label_style),d.appendChild(Ie),d.appendChild(Ma),y.appendChild(d),y.addEventListener("touchmove",function(a){a.stopPropagation()},!1),y.addEventListener("mousemove",function(a){a.stopPropagation()},!1),Ma.addEventListener("input",function(a){a.preventDefault();a.stopPropagation();E(!1);a=parseInt(Ma.value,10)-1;0<=$a[a]&&(xa(a),Ie.innerHTML=Df.replace("*",m+1));U()},!1),Cf=0,oi=-1,Ma.addEventListener("pointerup",function(a){return function(b){b.stopPropagation();
a.$jscomp$loop$prop$sfbounds$11()}}(k),!1),Ma.addEventListener("mouseup",function(a){return function(b){b.stopPropagation();a.$jscomp$loop$prop$sfbounds$11()}}(k),!1),Ma.addEventListener("change",function(a){return function(b){b.stopPropagation();a.$jscomp$loop$prop$sfbounds$11()}}(k),!1),Gg=!0);"framelabel"==h&&(Va=p("button"),pb&&(Va.className="framelabel"),Va.innerHTML="",null!=l&&(Va.title=l),hb=null,q=f.frame_labels,null!=q&&(hb=q.split(","),Va.innerHTML=hb[0]),d=Mc+f.framelabel_style,null!=
d&&Va.setAttribute("style",d),d=f.framelabel_position,null!=d&&(d=d.split(","),Va.style.position="absolute",Va.style.left=u.offsetLeft+parseInt(d[0],10)+"px",Va.style.top=u.offsetTop+parseInt(d[1],10)+"px"),y.appendChild(Va));if("autorefresh"==h||"autorefresh/off"==h)null!=Sc&&clearInterval(Sc),ad=p("button"),ea(ad,"autorefresh","Disable Auto Refresh","Enable Auto Refresh",l,"autorefresh"),ad.addEventListener("click",G.toggleAutoRefresh,!1),pe=!1,y.appendChild(ad),"autorefresh"==h?G.toggleAutoRefresh():
I(ad,!1,"autotoggle off");"backward"==h&&(yb=p("button"),ea(yb,"backward","<","<",l,"step back"),yb.addEventListener("click",function(){E(!1);sb(-1);U()},!1),y.appendChild(yb));"forward"==h&&(zb=p("button"),ea(zb,"forward",">",">",l,"step forward"),zb.addEventListener("click",function(){E(!1);sb(1);U()},!1),y.appendChild(zb));if("step"==h){d=f.step_labels;var S=null!=d?d.split(","):["<",">"];yb=p("button");pb&&(yb.className="step back");yb.innerHTML=S[0];yb.addEventListener("click",function(){E(!1);
sb(-1);U()},!1);d=Mc+f.step_style;null!=d&&yb.setAttribute("style",d);null!=l&&(yb.title=l);y.appendChild(yb);zb=p("button");pb&&(zb.className="step forward");zb.innerHTML=S[1];zb.addEventListener("click",function(){E(!1);sb(1);U()},!1);null!=d&&zb.setAttribute("style",d);null!=l&&(zb.title=l);y.appendChild(zb)}"first"==h&&(Pb=p("button"),ea(Pb,"first","|<","|<",l,"firstlast first"),Pb.addEventListener("click",function(){E(!1);xa(oa(0));U()},!1),y.appendChild(Pb));"last"==h&&(Qb=p("button"),ea(Qb,
"last",">|",">|",l,"firstlast last"),Qb.addEventListener("click",function(){E(!1);xa(oa(t-1));U()},!1),y.appendChild(Qb));"firstlast"==h&&(d=f.firstlast_labels,S=null!=d?d.split(","):["<<",">>"],Pb=p("button"),pb&&(Pb.className="firstlast"),Pb.innerHTML=S[0],Pb.addEventListener("click",function(){E(!1);xa(oa(0));U()},!1),d=Mc+f.firstlast_style,null!=d&&Pb.setAttribute("style",d),null!=l&&(Pb.title=l),y.appendChild(Pb),Qb=p("button"),pb&&(Qb.className="firstlast"),Qb.innerHTML=S[1],Qb.addEventListener("click",
function(){E(!1);xa(oa(t-1));U()},!1),null!=d&&Qb.setAttribute("style",d),null!=l&&(Qb.title=l),y.appendChild(Qb));"setspeed"==h?(Rb=p("input"),pb&&(Rb.className="setspeed"),Rb.type="range",Rb.min=hc,Rb.max=$c,Rb.value=$c-Ja,null!=l&&(Rb.title=l),d="vertical-align:middle;"+f.setspeed_style,Rb.setAttribute("style",d),Rb.addEventListener("input",function(a){Ja=$c-parseInt(Rb.value,10)+30;void 0!=Xd&&Xd(Ja);E(!0);U()},!1),y.appendChild(Rb)):"speed"==h&&(d=f.speed_labels,S=null!=d?d.split(","):["-","+"],
ic=p("button"),pb&&(ic.className="speed slower"),ic.innerHTML=S[0],ic.addEventListener("click",function(){Ja+=vg;jc.disabled=!1;Ja>$c&&(Ja=$c,ic.disabled=!0);void 0!=Xd&&Xd(Ja)},!1),d=Mc+f.speed_style,null!=d&&ic.setAttribute("style",d),null!=l&&(ic.title=l),y.appendChild(ic),jc=p("button"),pb&&(jc.className="speed faster"),jc.innerHTML=S[1],jc.addEventListener("click",function(){Ja-=vg;ic.disabled=!1;Ja<hc&&(Ja=hc,jc.disabled=!0);void 0!=Xd&&Xd(Ja)},!1),null!=d&&jc.setAttribute("style",d),null!=
l&&(jc.title=l),y.appendChild(jc));"zoom"==h&&(La=p("button"),ea(La,"zoom","Zoom","Un-zoom",l,"zoom off"),La.addEventListener("click",G.toggleZooming,!1),y.appendChild(La),Ia=!1);if("annotate"==h){Je=p("button");ea(Je,"annotate","Annotate","Finished",l,"annotate");ra=p("div");ra.setAttribute("style","position:absolute;box-sizing:content-box;height:120px;width:180px;top:20px;left:20px;z-index:15;visibility:hidden;background-color:lightgray;border-width:6px;border-style:solid;border-color:magenta;border-radius:25px;padding:10px;font:normal normal normal 16px Arial;color:black;");
ra.title="Drag this box around.  Select attributes, then go onto the image and click & drag";nd=od=20;Ef=Sb=!1;pi=3;qi=11;pd=Ke=0;r=[];ra.style["touch-action"]="none";var Fc=function(a){od=a.clientX-pd;nd=a.clientY-Ke;ra.style.top=nd+"px";ra.style.left=od+"px"};ra.addEventListener("mousedown",function(a){if(0!=a.clientX||0!=a.clientY)Ef=!0,pd=a.clientX-od,Ke=a.clientY-nd},!1);ra.addEventListener("mouseup",function(a){Ef=!1},!1);ra.addEventListener("mouseout",function(a){Ef&&Fc(a)},!1);ra.addEventListener("mousemove",
function(a){Ef&&Fc(a)},!1);window.PointerEvent?(ra.addEventListener("pointerdown",function(a){"mouse"!=a.pointerType&&(pd=a.clientX-od,Ke=a.clientY-nd)},!1),ra.addEventListener("pointermove",function(a){"mouse"!=a.pointerType&&(0==pd&&(pd=a.clientX,Ke=a.clientY),Fc(a))},!1)):ra.addEventListener("touchmove",function(a){a=a.changedTouches[0];0==pd&&(pd=a.clientX,Ke=a.clientY);Fc(a)},!1);Je.addEventListener("click",function(){if(Sb=!Sb){r=[];od=u.offsetLeft;nd=u.offsetTop;var a=f.annotate_position;null!=
a&&(a=a.split(","),od+=parseInt(a[0],10),nd+=parseInt(a[1],10));ra.style.top=nd+"px";ra.style.left=od+"px";ra.style.visibility="visible";I(Je,!1,"annotate off");aj=Ia;Ia=!1;null!=La&&(La.disabled=!0)}else ra.style.visibility="hidden",I(Je,!0,"annotate on"),Ia=aj,null!=La&&(La.disabled=!1);fa()},!0);Le=ri("Color Black White Red Green Blue Yellow Orange Cyan Magenta".split(" "),"black black white red green blue yellow orange cyan magenta".split(" "),function(a){});Nc=ri("Width 1 2 3 4 5 6 7 8 10 12 14 16 18 20 24 28 32 36 38".split(" "),
[1,1,2,3,4,5,6,7,8,10,12,14,16,18,20,24,28,32,36,38],function(a){6==Me.selectedIndex?qi=Nc.selectedIndex:pi=Nc.selectedIndex});Nc.title="Select width or font size";Me=ri("Type Arrow Circle Box Polygon Draw Text Line".split(" "),[-1,0,1,2,3,4,5,6],function(a){6==Me.selectedIndex?(Tb.focus(),Tb.select(),Nc.selectedIndex=qi):Nc.selectedIndex=pi;0==Le.selectedIndex&&(Le.selectedIndex=2)});d=p("button");d.style.width="70px";d.style.margin="5px";d.innerHTML="Erase";d.title="Erase last item";d.addEventListener("click",
function(){0<r.length&&(r.pop(),fa())},!1);Tb=p("input");Tb.type="text";Tb.style.width="150px";Tb.style.margin="5px";Tb.title="Enter your text here, then click where you want it";Tb.value="Text input";S=f.annotate_defaults;null!=S&&(S=S.split(","),Me.selectedIndex=parseInt(S[0],10),1<S.length&&(Le.selectedIndex=parseInt(S[1],10)),2<S.length&&(Nc.selectedIndex=parseInt(S[2],10)),3<S.length&&(Tb.value=S[3].trim()));S=p("div");S.innerHTML="Annotation Tools";var v=p("div");v.appendChild(Me);v.appendChild(Le);
var n=p("div");n.appendChild(Nc);n.appendChild(d);d=p("div");d.appendChild(Tb);ra.appendChild(S);ra.appendChild(v);ra.appendChild(n);ra.appendChild(d);y.appendChild(Je);u.appendChild(ra)}"saveall"==h&&(Ng=p("button"),ea(Ng,"saveall","SaveAll","SaveAll",l,"saveall"),si=f.saveall_prompt,sc=f.saveall_filename,d=f.saveall_list,ti=null==d?["0"]:d.split(","),Ng.addEventListener("click",function(){for(var a=0;a<ti.length;a++)for(var b=parseInt(ti[a],10),d=0;d<Ba.length;d++){0===d&&null!=si&&(sc=window.prompt(si,
sc),null!=sc&&1>sc.length&&(sc=null));var g=null==sc?"":-1!=sc.indexOf("#")?sc.replace("#",d.toString()):sc+d;var c=document.createElement("a");c.href=0==b?Ba[d]:T[d][b-1];c.download=g;c.click()}},!1),y.appendChild(Ng));if("capture"==h){Og=p("button");ea(Og,"capture","Capture","Capture",l,"capture");var A=f.capture_prompt;Pg=f.capture_filename;null==Pg&&(Pg="haimage.png");Og.addEventListener("click",function(){var a=Pg;if(null!=A&&(a=window.prompt(A,a),null==a))return;var b=p("canvas");b.height=tb.height;
b.width=tb.width;var d=b.getContext("2d");He=!1;fa();d.drawImage(tb,0,0);d.drawImage(Ac,0,0);He=!0;b.toBlob(function(b){var d=URL.createObjectURL(b),g=document.createElement("a");g.href=d;g.download=a;g.click();setTimeout(function(){URL.revokeObjectURL(b)},3E4)})},!1);y.appendChild(Og)}"show"==h&&(Qg=p("button"),ea(Qg,"show","Show","Show",l,"show"),Rg=f.show_prompt,bj=f.show_image_file,null==Rg&&(Rg="Right-click to save or copy the image<br> <font size='-1'>(to save in some browsers, you may need to first 'Open in New Tab')</font> <p>"),
Qg.addEventListener("click",function(){if(bj)window.open(Ba[m]);else{var a=tb.toDataURL("image/png;base64;");var b=window.open();b.document.write(Rg+"<img src="+a+"></img>")}},!1),y.appendChild(Qg));"toggle"==h&&($a=[],d=f.toggle_size,null!=d?(d=d.split(","),Yd=parseInt(d[0],10),Ff=parseInt(d[1],10),Gf=parseInt(d[2],10)):(Ff=Yd=10,Gf=3),ui="red",vi="blue",wi="orange",xi=!1,z(f.toggle_layout_width,"t")&&(xi=!0),d=f.toggle_colors,null!=d&&(d=d.split(","),vi=d[0].trim(),ui=d[1].trim(),wi=d[2].trim()),
Fb=p("div"),Fb.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;"),Fb.style.backgroundColor=y.style.backgroundColor,Fb.align=me,Sg=new PEvs(Fb,G.togdown,G.togup,null,G.togdown,null,null),Sg.setHysteresis(0),qd=p("canvas"),qd.height=2*Ff,Tg=qd.getContext("2d"),Fb.appendChild(qd),a?u.insertBefore(Fb,Xa):u.appendChild(Fb),d=f.toggle_onoff,Hf=null,
null!=d&&(Hf=d.split(",")),Ug=!0,null!=l&&(Fb.title=l));if("overlay"==h||z(h,"menu")){0==Ha&&(w=[]);S=f.overlay_tooltip;d=null;null!=S&&(d=S.split(","));S=f.overlay_radio;v=null;null!=S&&(v=S.split(","));var B=f.overlay_menu_links;n=null;null!=B&&(n=B.split(","));var D=f.overlay_labels_color;B=null;null!=D&&(B=D.split(","));var H=f.overlay_smoothing;D=null;null!=H&&(D=H.split(","));If=[];var F=H=gd=!1;z(h,"menu")&&(gd=!0,0<h.indexOf("/on")&&(H=!0),0<h.indexOf("/always")&&(F=!0));0==Ha&&(De=[]);var x=
f.overlay_caching;h=null;null==x&&(x=f.overlay_static);null!=x&&(h=x.split(","));var J=!0;null!=f.overlay_nonewdiv&&(J=!1);Ha++;for(x=0;x<fc.length;x++){var Q=fc[x].trim();If[x]=Bd;null!=D&&(z(D[x],"t")||z(D[x],"y")?If[x]=!0:If[x]=!1);if(0==x||0==Q.indexOf("/")){0==Q.indexOf("/")&&(Q=Q.substr(1));if(gd){ib[Ha]=p("div");ib[Ha].dropalways=F;var C="menu"+Ha+"_labels_style";ib[Ha].setAttribute("style","text-align:left;display:block;position:absolute;border-style:solid;border-width:2px;background:#ffffff;z-index:99;visibility:"+
(H||F?"visible":"hidden")+";"+(void 0==f[C]?f.overlay_labels_style:f[C]));Vg++}else J?(Ub=p("div"),Vg++,Ub.align="center",a?u.insertBefore(Ub,Xa):u.appendChild(Ub)):(Ub=p("span"),y.appendChild(Ub));q=f.overlay_labels_style;gd||null==q||Ub.setAttribute("style",q)}if(null==n||null!=n&&n[x]==Ha){C=!1;-1!=Q.indexOf("<a href=")&&(C=!0);var L=!1,K=!1,N=!1,O=!1;q=Q.length;C||(0<Q.indexOf("/on")&&Q.indexOf("/on")==q-3&&(L=!0),0<Q.indexOf("/always")&&Q.indexOf("/always")==q-7&&(K=L=!0),0<Q.indexOf("/hidden")&&
(N=!0),0<Q.indexOf("/hotspots")&&(O=!0),-1!=Q.indexOf("/")&&(Q=Q.substr(0,Q.indexOf("/"))));null!=h?z(h[x],"y")||z(h[x],"t")?De[x]=!0:De[x]=!1:De[x]=!0;w[x]=p("input");w[x].type="checkbox";w[x].value=Q;w[x].id=zf+Q;w[x].showMe=!(K&N)&!O;var M="vertical-align:middle;";q=f.checkbox_style;null!=q&&(M+=q);w[x].setAttribute("style",M);w[x].checked=L;w[x].restorableState=L;w[x].name=0;w[x].hotspotIndex=O;null!=Fa&&x==ub&&w[x].checked&&(Fa.disabled=!1);null!=Cc&&!Cc[x]&&L&&(Cd=!1);w[x].addEventListener("click",
G.overClick,!1);null!=S&&(q=v[x].indexOf("/"),-1!=q&&(w[x].name=v[x].substr(q+1).trim()),z(v[x],"t")&&(w[x].type="radio",-1==q&&(w[x].name="all")));w[x].isGhost=!0;K||N||(null!=d&&(w[x].title=d[x]),K=p("label"),K.htmlFor=zf+Q,null!=d&&(K.title=d[x]),K.innerHTML=Q,K.name=w[x].name,Q="vertical-align:middle;",null!=B&&(Q=Q+"color:"+B[x]+";"),K.setAttribute("style",Q),Q=p("span"),C||Q.appendChild(w[x]),Q.appendChild(K),gd?(Q.setAttribute("style","display:block;margin-right:5px;"),ib[Ha].appendChild(Q)):
(C="10",null!=gf&&(C=10+gf[x]),Q.setAttribute("style","margin-left:"+C+"px;"),Ub.appendChild(Q)),w[x].isGhost=!1)}}gd&&(rd[Ha]=p("button"),ea(rd[Ha],"menu"+Ha,"Show Overlay Menu","Hide Menu",l,"menu off"),rd[Ha].menuInx=Ha,rd[Ha].addEventListener("click",function(a){if("hidden"===ib[this.menuInx].style.visibility){for(a=1;a<ib.length;a++)ib[a].dropalways||"visible"!=ib[a].style.visibility||(ib[rd[a].menuInx].style.visibility="hidden",I(rd[a],!0,"menu off"));ib[this.menuInx].style.visibility="visible";
I(this,!1,"menu on")}else ib[this.menuInx].style.visibility="hidden",I(this,!0,"menu off")},!1),ib[Ha].dropalways||y.appendChild(rd[Ha]),u.insertBefore(ib[Ha],Xa));if(null==gc)for(gc=Array(fc.length),x=0;x<fc.length;x++)gc[x]=0;else for(x=0;x<fc.length;x++)Jb(x)}}Ca=!0;xf=null;q=f.start_looping;null!=q&&(d=q.split(","),z(d[0],"f")&&(Ca=!1),1<d.length&&(Mb=parseInt(d[1],10)-1,isNaN(Mb)&&(Mb=0),m=Mb),2<d.length&&(z(d[2],"t")&&(xf=!0),z(d[2],"f")&&(xf=!1)));E(Ca)}function Jb(b){var a;if(0>gc[b]){var g=
!1;for(a=0;a<fc.length;a++)gc[a]!=-gc[b]||g||(g=w[a].checked);w[b].checked=g}}function Yb(b){0==fb&&(gb=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");var a=b[4].trim(),g=b[4].indexOf("/"),d=b[4].indexOf("?"),c=-1,e=-1;-1!=g&&(c=parseInt(b[4].substring(g+1),10)-1,a=a.substring(0,g));-1!=d&&(e=parseInt(b[4].substring(d+1),10)-1,d<g||-1==g)&&(a=a.substring(0,d));gb[fb]=new nb(parseInt(b[0].trim(),10),parseInt(b[1].trim(),10),b[2].trim(),b[3].trim(),a.toLowerCase(),b[5].trim().toLowerCase(),b[6].trim(),
c,e,8<=b.length?b[7].trim():null,9==b.length?b[8].trim():null);fb+=1}function ie(b){0==vf&&(Za=[],wa=null);var a=b.substr(b.indexOf("=")+1).trim().split("(");b=a[0].split(",");var g=b[0].trim();0==g.indexOf("0x")&&(g="#"+g.substring(2));Za[vf]=new yc(g,b[1].trim(),b[2].trim(),b[3].trim(),a[1].trim());vf+=1}function Pa(b){0==Bb&&(Ra=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");Ra[Bb]=new Zb(parseInt(b[0],10)-1,parseInt(b[1],16),b[2].trim(),b[3].trim(),5==b.length?b[4].trim():"Click for details");
Bb+=1}function yc(b,a,g,d,c){this.color=b;this.alpha=1;7<this.color.length&&(this.alpha=parseInt(this.color.substring(7),16)/255,this.color=this.color.substring(0,7),.1>this.alpha&&(this.alpha=.1));this.action=a;this.value=g;this.tip=d;this.poly=c;b=c.split(",");this.xy=[];this.ymin=this.xmin=9999;for(a=this.ymax=this.xmax=0;a<b.length;a++)this.xy[a]=parseInt(b[a].trim(),10),0==a%2?(this.xy[a]<this.xmin&&(this.xmin=this.xy[a]),this.xy[a]>this.xmax&&(this.xmax=this.xy[a])):(this.xy[a]<this.ymin&&(this.ymin=
this.xy[a]),this.xy[a]>this.ymax&&(this.ymax=this.xy[a]));this.height=this.ymax-this.ymin+1;this.width=this.xmax-this.xmin+1;this.can=p("canvas");this.can.height=this.height;this.can.width=this.width;this.ctx=this.can.getContext("2d");this.ctx.imageSmoothingEnabled=!1;this.ctx.fillStyle=this.color;this.ctx.globalAlpha=this.alpha;this.ctx.beginPath();this.ctx.moveTo(this.xy[0]-this.xmin,this.xy[1]-this.ymin);for(a=2;a<this.xy.length;a+=2)this.ctx.lineTo(this.xy[a]-this.xmin,this.xy[a+1]-this.ymin);
this.ctx.closePath();this.ctx.fill()}function Zb(b,a,g,d,c){this.overlay=b;this.color=a;this.action=g;this.value=d;this.tip=c}function nb(b,a,g,d,c,e,f,l,k,h,q){this.x0=b;this.y0=a;this.icon=null;this.isIcon=!1;if("icon"==g)this.icon=new Image,this.icon.hotspot=this,Wg=!0,this.icon.onload=function(a){this.gotit=!0;this.hotspot.x1=this.hotspot.x0+this.width;this.hotspot.y1=this.hotspot.y0+this.height;this.hotspot.width=this.width;this.hotspot.height=this.height;this.hotspot.w2=this.width/2;this.hotspot.h2=
this.height/2;this.hotspot.isIcon=!0;this.hotspot.origX=0;this.hotspot.origY=0},this.y1=this.x1=-1,this.zoomme=this.fromfile=this.anim=!1,this.icon.gotit=!1,this.icon.src=d.trim();else if("sprite"==g||"spritefn"===g){this.x0=b;this.y0=a;this.inx=parseInt(d,10)-1;Ne=!1;xh?null!=qa&&(-1!=ed?this.inx>=ed&&this.inx<=ed+qa.length&&(Ne=!0):"spritefn"===g&&(Ne=!0)):Ne=!0;if(Ne){-1!=ed&&(this.inx-=ed);if(this.inx>=qa.length)return null;this.x1=qa[this.inx].width+b;this.y1=qa[this.inx].height+a;this.width=
qa[this.inx].width;this.height=qa[this.inx].height;this.w2=this.width/2;this.h2=this.height/2;this.origY=this.origX=0;this.icon=qa[this.inx].cloneNode();this.anim=qa[this.inx].anim;this.fromfile=qa[this.inx].fromfile;this.zoomme=qa[this.inx].zoomme;this.anim&&(this.icon.setAttribute("style","position:absolute;top:0px;left:0px;visibility:hidden;"),Jc.appendChild(this.icon))}else this.x1=dc[this.inx]+b,this.y1=ec[this.inx]+a,this.width=dc[this.inx],this.height=ec[this.inx],this.w2=dc[this.inx]/2,this.h2=
ec[this.inx]/2,this.origX=gg[this.inx],this.origY=hg[this.inx],this.icon=fg,this.zoomme=this.fromfile=this.anim=!1;Wg=this.isIcon=!0;this.icon.gotit=!0}else this.width=parseInt(g,10),this.height=parseInt(d,10),this.w2=this.width/2,this.h2=this.height/2,eg&&(this.x0=b-this.w2,this.y0=a-this.h2),this.x1=this.width+this.x0,this.y1=this.height+this.y0;this.pan=c;this.isPan=!1;"pan"===this.pan&&(this.isPan=!0);this.action=e;this.value=f;this.overlay=l;this.frame=k;this.tip=h;this.target=q}function $b(){if(Zd&&
!Md){ca=-1;for(var b=0;b<sa.length;b++)B>=sa[b]&&(ca=b)}}function rb(){null!=lc?Ea=lc.toLatLon(ja-Ic,ka-Hc):null!=Ag?(Ea[0]=Ag+(Vi-Ag)*(ka-Hc)/hd,Ea[1]=Bg+(Cg-Bg)*(ja-Ic)/Qd):(Ea[0]=Math.round(ja-Ic),Ea[1]=Math.round(ka-Hc))}function wd(b,a){"popup"==b.action?(null!=Xg&&Xg.close(),Xg=window.open("","HAniSPopup","scrollbars=yes,width="+Yh+",height="+Xh),Xg.document.write(Wh+b.value+"</div>")):"link"==b.action?(a=b.value,rb(),a=a.replace("%LATITUDE%",Ea[0].toFixed(4)),a=a.replace("%LONGITUDE%",Ea[1].toFixed(4)),
a=a.replace("%FRAMENUMBER%",m+1),a=a.replace("%FRAMENUMBERINDEX%",jg[m]),window.open(a,b.target?b.target:"_blank","")):"fof"==b.action&&(ia=Oh,G.resetZoom(),G.newFOF(b.value,!0),xc(a))}function Pc(){if(!Vc){var b=Th?Jd/B:0;N+b<Jd&&(N=Jd-b);b=Uh?Kd/B:0;N+za-b>ta-Kd&&(N=ta-za+b-Kd);b=Sh?Id/J:0;O+b<Id&&(O=Id-b);b=Rh?Hd/J:0;O+Aa-b>ua-Hd&&(O=ua-Aa-Hd+b);O=Math.round(O);N=Math.round(N)}}function je(b){var a=!1;b?Md?(ca--,0>ca?a=!0:(B=sa[ca],J=sa[ca])):(B-=.1*Ld/H,J-=.1*Ld/F):Md?(ca++,ca>=sa.length?(ca--,
ug&&(a=!0)):(B=sa[ca],J=sa[ca])):(!ug||B!==Zc&&J!==Zc||(a=!0),B+=.1*Ld/H,J+=.1*Ld/F,B>Zc&&(B=Zc),J>Zc&&(J=Zc));a||B<=wf||J<=Jf?(B=wf,J=Jf,ca=-1,ja=n,ka=A,O=N=0,Aa=ua,za=ta,Jd=Kd=Id=Hd=0,Sd&&(qb=!0)):(Hd=qg,Id=rg,Kd=tg,Jd=sg,N=ja-n/B,O=ka-A/J,Aa=Math.floor(ua/J),za=Math.floor(ta/B),Pc(),Sd&&(qb=!1));$b();void 0!=$d&&$d(["zoom",B,J,ja,ka,n,A,N,O,za,Aa])}function ac(){Kf=0;Vb=Array(2);Gb=Array(2);ae=Array(2);ab=0;Fd=null;xa(oa(0))}function E(b){Ga=!b;G.toggleIsLooping()}function ke(b,a,g,d,c,e,f,l){Pd.height=
c;Pd.width=d;ye.clearRect(0,0,d,c);ye.imageSmoothingEnabled=Bd;C.imageSmoothingEnabled=Bd;ye.drawImage(b,a,g,d,c,0,0,d,c);yi=ye.getImageData(0,0,d,c);sd=yi.data;Yg=cb[l];Zg=db[l];$g=eb[l];ah=ve[l];cj=4*d*c;for(tc=0;tc<cj;tc+=4)jb=sd[tc],jb===sd[tc+1]&&jb===sd[tc+2]&&(sd[tc]=Yg[jb],sd[tc+1]=Zg[jb],sd[tc+2]=$g[jb],sd[tc+3]=ah[jb]);ye.putImageData(yi,0,0);C.drawImage(Pd,e,f,W,aa)}function I(b,a,c){null!=b&&(a?(null!=b.style_on&&b.setAttribute("style",b.style_on),b.innerHTML=b.label_on):(null!=b.style_off&&
b.setAttribute("style",b.style_off),b.innerHTML=b.label_off),pb&&(b.className=c))}function Ka(b,a){if(!(b>=t)&&(-2==$a[b]&&(a=-2),$a[b]=a,Gg&&1==a&&(Ma.value=b+1,Ie.innerHTML=Df.replace("*",b+1)),Ug)){b=zi+b*(Yd+Gf);var c=wi;0==a?c=vi:-1==a?c=ui:-2==a&&(c=zh);Tg.fillStyle=c;Tg.fillRect(b,Ff/2,Yd,Ff)}}function Ue(b,a){Ug&&(qd.width=xi?parseInt(u.style.width,10):W,Tg.clearRect(0,0,qd.width,qd.height),zi=qd.width/2-b*(Yd+Gf)/2);for(var c=0;c<b;c++)a?-1!=qe?Ka(c,-2):null!=Hf&&"n"==Hf[c].toLowerCase().trim()?
Ka(c,-1):Ka(c,0):Ka(c,$a[c])}function xa(b){Ka(m,0);m=b;Ka(m,1);null!=Va&&null!=hb&&null!=hb[m]&&(Va.innerHTML=hb[m]);void 0!=Lf&&Lf(m)}function oa(b){b>=t&&(b=t-1);if(0<=$a[b])return b;var a=-1,c=b;0==c&&(a=1);for(var d=0;d<t-1;d++)if(c+=a,0<=$a[c])return c;return b}function sb(b){Ka(m,0);var a=b;do 0<a?(a=oa(t-1),m+=1,m>a&&(Oe&&Ga?(m=a,b=-b,Db&&E(!1)):Db?(m=a,E(!1)):m=oa(0))):(a=oa(0),--m,m<a&&(Oe&&Ga?(m=a,b=-b,Db&&E(!1)):Db?(m=a,E(!1)):m=oa(t-1))),a=b;while(0>$a[m]);Db=Mf;void 0!=Lf&&Lf(m);Fe=
a;Ka(m,1);null!=Va&&null!=hb&&null!=hb[m]&&(Va.innerHTML=hb[m])}function ob(b,a,c,d,e,f,k){this.bg=b;null!=b&&0==this.bg.indexOf("0x")&&(this.bg="#"+this.bg.substring(2));this.fg=a;null!=a&&0==this.fg.indexOf("0x")&&(this.fg="#"+this.fg.substring(2));this.font=c;this.fontHeight=Math.round(1.1*parseInt(c,10));this.scolor=d;null!=d&&0==this.scolor.indexOf("0x")&&(this.scolor="#"+this.scolor.substring(2));this.sblur=e;this.sxoff=f;this.syoff=k}function Wa(b,a,c,d,e){k.globalAlpha=1;k.font=b.font;var g=
b.fontHeight;c=c-g-6;var f=k.measureText(d).width;1==e&&(a-=f);0==e&&(a-=f/2);5>a&&(a=5);5>c&&(c=5);c+g+3>aa&&(c=aa-g-6);a+3+f>W&&(a=W-f-6);k.save();k.beginPath();k.fillStyle=b.bg;null!=b.scolor&&(k.shadowColor=b.scolor,k.shadowBlur=b.sblur,k.shadowOffsetX=b.sxoff,k.shadowOffsetY=b.syoff);Nf=a-3;bh=c;Ai=f+6;ch=g+6;k.fillRect(Nf,bh,Ai,ch);k.closePath();k.restore();k.textBaseline="bottom";k.fillStyle=b.fg;k.fillText(d,a,c+g+3)}function fa(){k.clearRect(0,0,W,aa);dh=!1;if(kb){k.beginPath();k.lineWidth=
2;k.strokeStyle="white";var b=ab;1<b&&(b=2);for(var a=0;a<b;a++)1<ab&&(k.moveTo(Vb[0]/H,Gb[0]/F),k.lineTo(Vb[1]/H,Gb[1]/F)),k.moveTo(Vb[a]/H-15,Gb[a]/F),k.lineTo(Vb[a]/H+15,Gb[a]/F),k.moveTo(Vb[a]/H,Gb[a]/F-15),k.lineTo(Vb[a]/H,Gb[a]/F+15);k.closePath();k.stroke();if(3==ab){var c=Y,d=M;k.moveTo(c,d);k.fillStyle=Dc;k.fillRect(c-2,d-2,5,5);b=be;a=Math.round(c+Of/H*Pe*(be-ae[1]));for(var e=Math.round(d+Qe/F*Pe*(be-ae[1])),f=0;300>f;f++){k.beginPath();k.lineWidth=1;k.strokeStyle=Dc;k.moveTo(c,d);k.lineTo(a,
e);k.stroke();k.beginPath();k.lineWidth=3;k.rect(a-2,e-2,5,5);k.stroke();if(3>a||a+3>W||3>e||e+3>aa)break;d=mc+b;d=100*Math.floor(d/60)+d%60;d%=2400;Jh?(c="AM",1200<=d?(1300<=d&&(d-=1200),c="PM"):100>d&&(d+=1200),c=Math.floor(d/100)+":"+Math.floor(Math.floor(d%100)/10)+Math.floor(d%10)+" "+c):(c=d+" ",1E3>d&&(c="0"+d),100>d&&(c="00"+d),10>d&&(c="000"+d));d=0;Math.abs(eh)<Ed+5&&(d=45*Wb);var h=e;0>Bi*eh&&0==d&&(h=e+Ed);k.font=se;c=c+" "+Ih;var l=k.measureText(c).width;k.fillStyle=re;0===d?(k.fillRect(a+
2,h-Ed-2+d,l+4,Ed+3),k.fillStyle=Dc,k.textBaseline="bottom",k.fillText(c,a+5,h)):(k.save(),k.translate(a+5,e),k.rotate(d),k.fillRect(2,-2,l+4,Ed+3),k.fillStyle=Dc,k.textBaseline="bottom",k.fillText(c,5,Ed),k.restore());c=a;d=e;a=Math.round(c+Pe*Bi);e=Math.round(d+Pe*eh);b+=da}}null!=Fd&&Wa(mg,dj,ej,Fd,0);He&&(Wa(Qi,9999,di,ci[Kf],0),Ci=Nf,Di=bh,Ei=bh+ch)}if(Eb){He&&(0==Wd?Wa(ni,9999,10,mf[0],0):(Wa($i,10,10,mf[1],0),fj=Nf+Ai,Wa(ni,9999,10,mf[2],0)),gj=Nf,hj=ch);k.beginPath();k.lineWidth=2;k.strokeStyle=
ei;for(b=0;b<va.length;b+=2)0==b?k.moveTo(va[b]/H,va[b+1]/F):k.lineTo(va[b]/H,va[b+1]/F);nf&4<va.length&&k.lineTo(va[0]/H,va[1]/F);k.stroke();for(b=0;b<va.length;b+=2)k.beginPath(),k.rect(va[b]/H-2,va[b+1]/F-2,5,5),k.stroke()}if(Sb)for(b=0;b<r.length;b++){c=r[b].type;k.beginPath();k.strokeStyle=r[b].color;k.lineWidth=r[b].width;if("0"==c||"6"==c)a=Math.atan2(r[b].xe-r[b].x,r[b].ye-r[b].y),e=r[b].x+r[b].width*Math.sin(a),f=r[b].y+r[b].width*Math.cos(a),k.beginPath(),k.moveTo(e,f),k.lineTo(r[b].xe,
r[b].ye),"0"==c&&(c=12+r[b].width/5,d=30*Wb,k.moveTo(e+c*Math.sin(a-d),f+c*Math.cos(a-d)),k.lineTo(e,f),k.lineTo(e+c*Math.sin(a+d),f+c*Math.cos(a+d)));else if("1"==c)k.arc(r[b].x,r[b].y,r[b].size,0,2*Math.PI);else if("2"==c)k.rect(r[b].x-r[b].size,r[b].y-r[b].size,2*r[b].size,2*r[b].size);else if("3"==c){k.moveTo(r[b].xp[0],r[b].yp[0]);for(e=1;e<r[b].xp.length;e++)k.lineTo(r[b].xp[e],r[b].yp[e]);k.lineTo(r[b].xp[0],r[b].yp[0])}else if("4"==c)for(k.moveTo(r[b].xp[0],r[b].yp[0]),e=1;e<r[b].xp.length;e++)k.lineTo(r[b].xp[e],
r[b].yp[e]);else"5"==c&&(k.fillStyle=r[b].color,k.font=r[b].width+"pt arial",a=k.measureText(r[b].text).width,k.fillText(r[b].text,r[b].x-a/2,r[b].y+r[b].width/2));k.stroke()}ld&&(Y=pa.getX(),n=Y*H,ja=N+n/B,M=pa.getY(),A=M*F,ka=O+A/J,k.beginPath(),k.strokeStyle=rh,k.lineWidth=3,k.moveTo(fh/H,gh/F),k.lineTo(Pf/H,Qf/F),k.stroke(),k.closePath(),rb(),zd?(td=Wb*ce[0],ud=Wb*Ea[0],Re=Wb*ce[1],Se=Wb*Ea[1],hh=Math.pow(Math.sin((ud-td)/2),2)+Math.cos(td)*Math.cos(ud)*Math.pow(Math.sin((Se-Re)/2),2),hh=12742.02*
bf*Math.asin(Math.min(1,Math.sqrt(hh))),b=" "+hh.toFixed(bg)+" "+Ad+" ",ne&&(a=z(ne,"t")?(Math.atan2(Math.sin(Se-Re)*Math.cos(ud),Math.cos(td)*Math.sin(ud)-Math.sin(td)*Math.cos(ud)*Math.cos(Se-Re))/Wb+360)%360:(Math.atan2(Math.sin(Re-Se)*Math.cos(td),Math.cos(ud)*Math.sin(td)-Math.sin(ud)*Math.cos(td)*Math.cos(Re-Se))/Wb+360)%360,b=b+" ("+a.toFixed(0)+"\u00b0)")):(a=Rc*(ce[0]-Ea[0]),e=$e*(ce[1]-Ea[1]),b=" "+Math.sqrt(a*a+e*e).toFixed(bg)+" "+Ad+" ",ne&&(a=Math.atan2(-a,e)/Wb,0>a&&(a+=360),z(ne,"f")&&
(a+=180),360<a&&(a-=360),b=b+" ("+a.toFixed(0)+"\u00b0)")),Wa(Oi,Pf/H+10,Qf/F,b,-1));Ob&&Wa(Nh,Fi,Gi,Hi,-1);if(cc||Ud||ef)if(Y=pa.getX(),n=Y*H,M=pa.getY(),A=M*F,0<=n&&0<=A){ja=N+n/B;ka=O+A/J;if(Ud){rb();b=Ea[1];zd&&180<b&&(b-=360);zd&&360<b&&(b-=360);ij=Xe+Ea[0].toFixed(Zf)+"  "+Ye+b.toFixed(Zf);b=M;if(ld||Ob)b=M+qh.fontHeight+6;Wa(qh,Y+10,b,ij,-1)}if(ef)for(k.fillStyle=vh,b=0;b<fb;b++)if(a=gb[b],a.isPan){if(ja>=a.x0&&ja<=a.x1&&ka>=a.y0&&ka<=a.y1){(-1===a.overlay||w[a.overlay].checked)&&k.fillRect((a.x0-
N)*B,(a.y0-O)*J,a.width*B,a.height*J);break}}else if(n>a.x0&&n<a.x1&&A>a.y0&&A<a.y1){(-1===a.overlay||w[a.overlay].checked)&&k.fillRect(a.x0,a.y0,a.width,a.height);break}if(cc&&bd&&kd)if(ja=Math.round(ja),ka=Math.round(ka),cg)bb.clearRect(0,0,1,1),bb.drawImage(Sa[m],ja-Ic,ka-Hc,1,1,0,0,1,1),ba=bb.getImageData(0,0,1,1).data,V=0,le(!1);else for(a=0;a<X;a++)if(b=X-a-1,L[m][b].gotit&&w[b].checked&&(b==ub||null!=Bc[b]&&0<=Bc[b])){bb.clearRect(0,0,1,1);b==ub?bb.drawImage(oc[m],ja-Ic,ka-Hc,1,1,0,0,1,1):
bb.drawImage(L[m][b],ja-Ic,ka-Hc,1,1,0,0,1,1);ba=bb.getImageData(0,0,1,1).data;V=Bc[b];null!=V&&le(b==ub||hi);break}}!qb||kb||bc||cc||null==wa||(k.drawImage(wa.can,0,0,wa.width,wa.height,wa.xmin/H,wa.ymin/F,wa.width/H,wa.height/F),Wa(Nh,(wa.xmin+wa.xmax)/2/H,(wa.ymin+wa.ymax)/2/F,wa.tip,0),dh=!0)}function le(b){Rf=999;uc=sh;var a=Ab[V].length-1;if(0==ba[3])uc=qf[V];else{if(th)vc=ba[0];else if(b)ih=0,vc=ba[0],Rf=0;else for(var c=0;c<a;c++)wc[0]=ba[0]-cb[V][c],0>wc[0]*(cb[V][c+1]-ba[0]-1)||(wc[1]=ba[1]-
db[V][c],0>wc[1]*(db[V][c+1]-ba[1]-1)||(wc[2]=ba[2]-eb[V][c],0>wc[2]*(eb[V][c+1]-ba[2]-1)||(de=zg[V][c],jh=wc[de]/fd[V][c][de],Ii=Math.abs(wc[Ji[de]]-jh*fd[V][c][Ji[de]])+Math.abs(wc[Ki[de]]-jh*fd[V][c][Ki[de]]),Ii<Rf&&(vc=c,Rf=Ii,ih=jh))));if(999>Rf)uc=dd[V][vc],-1!=kc[V][vc]&&(Li=Ab[V][vc],0!=ih&&(Li+=ih*(Ab[V][vc+1]-Ab[V][vc])),uc=uc+" "+Li.toFixed(kc[V][vc])+" "+cd[V][vc]);else if(b||0<oe){var d=-1;if(b)d=ba[0];else for(c=0;c<a;c++)if(Math.abs(ba[0]-cb[V][c])<oe&&Math.abs(ba[1]-db[V][c])<oe&&
Math.abs(ba[2]-eb[V][c])<oe){d=c;break}-1!=d&&(uc=dd[V][d],-1!=kc[V][d]&&(uc=uc+" "+Ab[V][d].toFixed(kc[V][d])+" "+cd[V][d]))}}"hide"!=uc&&Wa(Pi,Y-10,M,uc,1)}function U(){kh=N-Ic;0>kh?(ee=0,fe=-kh*W/za):(ee=kh,fe=0);lh=O-Hc;0>lh?(ge=0,he=-lh*aa/Aa):(ge=lh,he=0);if(kd)try{C.clearRect(0,0,W,aa);C.globalAlpha=1;if(!Vh)if(Zd&&null!=pc&&0<=ca&&pc[ca].gotit)C.drawImage(pc[ca],N*sa[ca],O*sa[ca],za*sa[ca],Aa*sa[ca],0,0,W,aa);else if(Sa[m].gotit&&(null!=ig?ke(Sa[m],ee,ge,za,Aa,fe,he,ig):C.drawImage(Sa[m],
ee,ge,za,Aa,fe,he,W,aa)),null!=Qa&&(C.globalAlpha=1,Sa[m].gotit))for(var b=0;b<Qa.length;b+=4)C.drawImage(Sa[m],Qa[b],Qa[b+1],Qa[b+2],Qa[b+3],Qa[b]/H,Qa[b+1]/F,Qa[b+2]/H,Qa[b+3]/F);if(0<X){for(b=0;b<X;b++){var a=null!=Wc?Wc[b]:b;C.imageSmoothingEnabled=If[a];!kg[a]&&w[a].checked&&w[a].showMe&&(null!=hf&&(C.globalAlpha=hf[a]),Zd&&0<=ca&&null!=Da&&void 0!=Da[a]&&Da[a][ca][m].gotit?C.drawImage(Da[a][ca][m],N*sa[ca],O*sa[ca],za*sa[ca],Aa*sa[ca],0,0,W,aa):L[m][a].gotit&&(null==Xc||1===Xc[a]?null!=Tc&&
0<=Tc[a]?ke(L[m][a],ee,ge,za,Aa,fe,he,Tc[a]):C.drawImage(L[m][a],ee,ge,za,Aa,fe,he,W,aa):0===Xc[a]&&C.drawImage(L[m][a],ee,ge,za,Aa,fe,he,W,aa)))}if(null!=vb)for(C.globalAlpha=1,b=0;b<X;b++)if(a=null!=Wc?Wc[b]:b,L[m][a].gotit&&(Hh[a]||w[a].checked)&&vb[a])for(var c=0;c<la[a].length;c++)C.drawImage(null!=L[m][a].origImage?L[m][a].origImage:L[m][a],la[a][c][0],la[a][c][1],la[a][c][2],la[a][c][3],la[a][c][4]/H,la[a][c][5]/F,la[a][c][2]/H,la[a][c][3]/F)}cc&&fa();mi&&Qc();if(Wg)for(C.globalAlpha=1,a=0;a<
fb;a++)if(null!=gb[a]){var d=gb[a];null!=d.icon&&(d.icon.style.visibility="hidden");if((-1==d.frame||d.frame==m)&&null!=d.icon&&d.icon.gotit&&(-1==d.overlay||-1!=d.overlay&&w[d.overlay].checked)){if(d.isPan){d.zoomme&&(d.icon.style.width=Math.round(d.width*B)+"px",d.icon.style.height=Math.round(d.height*J)+"px",d.w2=Math.round(d.width*B/2),d.h2=Math.round(d.height*J/2));var e=Math.round(((d.x0-N)*B-d.w2)/H);var f=Math.round(((d.y0-O)*J-d.h2)/F);if(d.anim){if(0>=e+d.icon.width||e>=ta||0>=f+d.icon.height||
f>=ua)continue;d.icon.style.top=f+"px";d.icon.style.left=e+"px"}else C.drawImage(d.icon,d.origX,d.origY,d.width,d.height,e,f,d.width/H,d.height/F)}else C.drawImage(d.icon,d.origX,d.origY,d.width,d.height,d.x0/H,d.y0/F,d.width/H,d.height/F);d.icon.style.visibility="visible"}}Sf&&(Tf.addFrame(C,{copy:!0,delay:Mi}),m==oa(t-1)&&(Sf=!1,E(Ca),Tf.render()))}catch(P){ha("Error:"+P)}}function ya(b,a,c){!lf||c>=a||(C.save(),C.fillStyle="blue",C.strokeStyle="white",C.lineWidth=3,C.strokeRect(rf,sf,200,18),C.fillRect(rf,
sf,c/a*200,18),a=C.measureText(b).width,C.fillStyle="orange",C.font="14px arial",C.fillText(b,rf+100-a/2,sf+14),C.restore())}function Qc(){lf&&nc>Ta?ya("Loading Images",nc,Ta):(mi=!1,Yf&&(zc.style.visibility="hidden"));Ta>=nc&&(Ga||xa(oa(m)),null!=yd&&(Fa.value=yd,G.doEnhance(null),yd=null),void 0!=tf&&tf(!0),null!=Cb&&(Cb.disabled=!1),null!=Nb&&(Nb.disabled=!1))}function ha(b){if(Ve&&Xf&&!Xf.closed)try{Xf.document.write(b+"<br>")}catch(a){}}function Zi(){Ga&&sb(Fe);Mi=m==oa(t-1)?uh+Ja:Ja;U();setTimeout(function(){qj(Zi)},
Mi)}function Uf(b){for(;-180>b;)b+=360;for(;180<b;)b-=360;return b}function oj(){var b,a,c,d,e,f,k,l,h=Math.PI/180;this.init=function(d){for(var c=[],g=1;g<d.length;g++)c[g]=parseFloat(d[g]);a=c[1];b=c[4]/c[5];e=c[6];f=c[7];d=this.toXY(c[2],c[3]);e=d[0];f=d[1]};this.toXY=function(g,l){c=b*Uf(l-a)*h-e;d=-b*g*h-f;return[c,d]};this.toLatLon=function(d,c){k=-(c+f)/b/h;l=Uf((d+e)/b/h+a);return[k,l]}}function nj(){var b,a,c,d,e,f,k,l,h,q,p,t,r,m,v,n,z,y,A,x,u,D,B,H,C,w,E,F,J,I,K,G=Math.PI/180;this.init=
function(d){for(var c=[],e=1;e<d.length;e++)c[e]=parseFloat(d[e]);b=c[1];a=c[2];x=0==c[8]?!1:!0;u=c[6];D=u*u;B=D*D;H=B*D;C=B*B;k=c[5]/c[7];K=c[7];x?(l=Math.cos(G*b),h=Math.sin(G*b)):(l=Math.cos(-b*G),h=Math.sin(-b*G));z=l/Math.sqrt(1-D*h*h);A=(1-u*h)/(1+u*h);n=x?Math.tan(Math.PI/4-b*G/2)/Math.pow(A,u/2):Math.tan(Math.PI/4- -b*G/2)/Math.pow(A,u/2);m=c[9];v=c[10];d=this.toXY(c[3],c[4]);m=d[0];v=d[1]};this.toXY=function(g,l){x?(e=G*g,f=G*(l-a)):(e=G*-g,f=G*(a-l));A=(1-u*Math.sin(e))/(1+u*Math.sin(e));
y=Math.tan(Math.PI/4-e/2)/Math.pow(A,u/2);w=90!=b&&-90!=b?k*z*y/n:2*k*K*y/Math.sqrt(Math.pow(1+u,1+u)*Math.pow(1-u,1-u));c=w*Math.sin(f);d=w*Math.cos(f);x||(c=-c,d=-d);q=c-m;p=d-v;return[q,p]};this.toLatLon=function(g,f){c=g+m;d=f+v;w=Math.sqrt(c*c+d*d);y=90==b||-90==b?w*Math.sqrt(Math.pow(1+u,1+u)*Math.pow(1-u,1-u))/(2*k*K):w*n/(k*z);E=Math.PI/2-2*Math.atan(y);F=Math.sin(2*E);J=Math.sin(4*E);I=Math.sin(6*E);e=E+F*D/2+5*F*B/24+F*H/12+13*F*C/360+7*J*B/48+29*J*H/240+811*J*C/11520+7*I*H/120+81*I*C/1120+
4279*Math.sin(8*E)*C/161280;x?(t=e/G,r=Math.atan2(c,d)/G+a):(t=-e/G,r=-Math.atan2(-c,-d)/G+a);return[t,Uf(r)]}}function pj(){var b,a,c,d,e,f,h,l,k,q,p,t,u,r,m,v,n,z,y,x,A,D,B,w,C,E,H,G,F,J,I,K,L,N,O,M=Math.PI/180;this.init=function(d){for(var e=[],g=1;g<d.length;g++)e[g]=parseFloat(d[g]);b=e[1];a=e[2];c=e[3];w=e[7];C=w*w;E=C*C;H=E*C;G=E*E;l=e[6]/e[8];k=Math.cos(M*b);q=Math.cos(M*a);t=Math.sin(b*M);p=Math.sin(a*M);A=k/Math.sqrt(1-C*t*t);D=q/Math.sqrt(1-C*p*p);y=Math.sqrt((1-t)/(1+t)*Math.pow((1+w*
t)/(1-w*t),w));x=Math.sqrt((1-p)/(1+p)*Math.pow((1+w*p)/(1-w*p),w));I=(Math.log(A)-Math.log(D))/(Math.log(y)-Math.log(x));K=A/(I*Math.pow(y,I));N=l*K*Math.pow(y,I);n=e[9];z=e[10];d=this.toXY(e[4],e[5]);n=d[0];z=d[1]};this.toXY=function(a,b){f=M*a;h=M*Uf(b-c);O=Math.sin(f);B=Math.sqrt((1-O)/(1+O)*Math.pow((1+w*O)/(1-w*O),w));J=l*K*Math.pow(B,I);L=I*h;d=J*Math.sin(L);e=N+J*Math.cos(L);u=d-n;r=e-z;return[u,r]};this.toLatLon=function(a,b){d=a+n;e=b+z;J=Math.abs(I)/I*Math.sqrt(d*d+(N-e)*(N-e));B=Math.pow(J/
(l*K),1/I);F=Math.PI/2-2*Math.atan(B);L=0>I?Math.atan(-d/(e-N)):Math.atan(d/(N-e));h=L/I;f=F+(C/2+5/24*E+H/12+13/360*G)*Math.sin(2*F)+(7/48*E+29/240*H+811/11520*G)*Math.sin(6*F)+(7/120*H+81/1120*G)*Math.sin(6*F)+4279/161280*G*Math.sin(8*F);m=f/M;v=Uf(c-h/M);return[m,v]}}var G=this,yh,aa,W,ua,ta,hd,Qd,H,F,Ic,Hc,fi,gi,Pb,Qb,zc,Yf,pa,Ve,Xg,Xf,Mc,mh,Vc,u,y,yf,Af,Xa,zf,Jc,ze,jj,kj,tb,C,bb,Ac,k,xe,Jg,kh,lh,ee,ge,fe,he,Yc,ng,kf,li,og,Kc,t,Ba,Zh,ib,gd,Ha,rd,X,kg,fc,Wc,T,Lc,gc,Gd,ia,Oh,Sa,L,Eg,Wi,ii,w,hf,
De,Ob,Hi,Fi,Gi,Dd,Kb,Ah,K,Bh,we,Fg,Y,M,n,A,ja,ka,za,Aa,N,O,He,pb,Mb,Yi,Ga,Ca,xf,m,Lf,Fe,Oe,$d,Gc,Od=!0,ff,Bf,Mg,Lg,Ze,We,f,Ja,hc,$c,Xd,tf,vg,uh,Mi,Bd,wh,If,Fa,Rd,Uc,ub,yd,Ya,oc,id,Ce,Hg,uf,ig,Pd,ye,yi,sd,jb,Yg,Zg,$g,ah,cj,tc,Tc,$a,Yd,Ff,Gf,xi,Fb,zi,Sg,nh,ui,vi,wi,qe,zh,gb,fb,Wg,pg,ef,eg,vh,yg,qa,ed,Ne,ji,Bb,Ra,ba,oh,Za,vf,qb,Sd,Ig,Be,wa,dh,Cc,Cd,sa,ca,pc,jd,Da,Ua,Zd,hb,Va,Oc,Ug,Hf,qd,Tg,kd,xd,Lb,zb,yb,Rb,jc,ic,gf,Cb,Sf,Tf,Nb,Nd,md,Eb,Wd,mf,wg,nf,pf,ei,va,$i,ni,gj,fj,hj,qc,kb,ab,Vb,Gb,ae,Ci,ci,Di,
Ei,di,Qi,xb,Pe,Of,Qe,Ni,Wb,ue,Dg,Bi,eh,be,da,Kf,mc,jf,Ih,Dc,re,se,Ed,Jh,Kh,bj,Qg,Rg,Og,Pg,Je,r,Ng,si,sc,ti,ra,Sb,pd,Ke,od,nd,Ef,aj,Me,Le,Nc,Tb,pi,qi,La,Qh,Ph,Ld,B,J,wf,Jf,bi,Ec,te,ai,$h,Ia,Zc,Md,Vf,ug,Ch=!1,Dh,Eh,Fh,lg,Gh,Db,Mf,Cf,oi,Ee,Ge,Ma,Df,Ie,Gg,rc,bc,fh,gh,bg,af,zd,Nf,bh,Ai,ch,ki=!0,Ae,ph,Pf,Qf,Oi,rh,ag,Na,$f,cf,ld,Rc,$e,Ad,ne,td,ud,Re,Se,hh,bf,Nh,jg,Td,Ud,Zf,Xe,Ye,qh,lc,Ea,ce,ij,Ag,Bg,Vi,Cg,Qa,Ub,Vg,Xc,vb,la,Hh,Kg,of,ad,Wh,Yh,Xh,Bc,cc,Vd,df,bd,cd,dd,kc,de,Rf,Pi,sh,oe,th,cg,mg,Lh,Mh,Fd,dj,
ej,vc,ih,jh,Ji,Ki,wc,V,Ii,uc,Li,Ab,v,fd,hi,cb,db,eb,ve,zg,qf,lj,pe,dg,Sc,lf,fg,gg,hg,dc,ec,xh,mi,rf,sf,Ta,nc,Hd,Vh,qg,Id,rg,Jd,sg,Rh,Sh,Uh,Th,Kd,tg,me,wb,rj="N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N".split(" "),qj=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||function(b){setTimeout(b,10)},p=function(b){return document.createElement(b)},z=function(b,a){return null==b?!1:0==b.trim().toLowerCase().indexOf(a)},
Xi=function(b,a){if(null!=b)return b=b.trim(),b.lastIndexOf(a)===b.length-1},Ui=function(b){void 0==mh&&(mh=p("textarea"));mh.innerHTML=b;return mh.value},ri=function(b,a,c){var d=p("select");d.style.width="70px";d.style.margin="5px";for(var e=0;e<b.length;e++){var g=p("option");g.innerHTML=b[e];g.value=a[e];d.add(g)}d.addEventListener("change",c,!1);return d},Ti=function(b){b=b.split(",");T=Array(t);for(var a=0;a<b.length;a++){var c=b[a].split("&");X=b.length;for(var d=0;d<t;d++)0===a&&(T[d]=Array(X)),
T[d][a]=c[1==c.length?0:d].trim(),null!=wb?T[d][a]=(wb+T[d][a]).trim():null!=ia&&(T[d][a]=(ia+T[d][a]).trim())}xd=!1},Ri=function(b){b=b.split(",");t=b.length;Ba=Array(t);for(var a=0;a<t;a++)Ba[a]=null!=ia?ia+b[a].trim():b[a].trim();xd=!1;t>X&&(X=0)},Si=function(b,a,c){var d=b;null!=ia&&(d=ia+b);Ba=Array(t);for(var e=0;e<t;e++){b=e*c+a;if(0<=d.indexOf("*"))Ba[e]=d.replace("*",b);else if(0<=d.indexOf("?")){for(var g=d;0<=g.lastIndexOf("?");){var h=g.lastIndexOf("?");g=g.substring(0,h)+b%10+g.substring(h+
1);b=Math.floor(b/10)}Ba[e]=g}else Ba[e]=d+e;ha("image filename = "+Ba[e])}z(f.reverse_order,"t")&&Ba.reverse();xd=!1;t>X&&(X=0)};HTMLCanvasElement.prototype.toBlob||Object.defineProperty(HTMLCanvasElement.prototype,"toBlob",{value:function(b,a,c){c=window.atob(this.toDataURL(a,c).split(",")[1]);for(var d=c.length,e=new Uint8Array(d),g=0;g<d;g++)e[g]=c.charCodeAt(g);b(new Blob([e],{type:a||"image/png"}))}});this.setup=function(b,a,e,d){void 0==a&&(a="MORdivcan");zf=a;Ae=e;void 0!=Ae&&"function"!=
typeof Ae&&(Ae=null);ph=void 0!=d?d.split("\n"):null;u=document.getElementById(a);me="center";u.align=me;Xa=p("div");Xa.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;");tb=p("canvas");tb.setAttribute("style","position:absolute;top:0;left:0;z-index:1;");C=tb.getContext("2d");Ac=p("canvas");Ac.setAttribute("style","position:absolute;top:0;left:0;z-index:12;");
k=Ac.getContext("2d");k.imageSmoothingEnabled=!1;xe=p("canvas");xe.setAttribute("style","position:absolute;top:0;left:0;z-index:10;");Jg=xe.getContext("2d");Jg.imageSmoothingEnabled=!1;Jc=p("div");Jc.setAttribute("style","position:absolute;top:0;left:0;z-index:5;overflow:hidden;border-width:0px;padding:0px;margin:0px;");ze=p("div");ze.setAttribute("style","position:absolute;top:0;left:0;z-index:10;overflow:hidden;border-width:0px;padding:0px;margin:0px;");ze.appendChild(xe);Pd=p("canvas");Xa.appendChild(ze);
Xa.appendChild(tb);Xa.appendChild(Ac);Xa.appendChild(Jc);u.appendChild(Xa);pa=new PEvs(Xa,G.down,G.up,G.move,G.drag,null,G.canTip);u.setAttribute("tabindex",0);u.addEventListener("keyup",function(a){Sb||We||(Lg=Mg=Bf=!1,Ze&&(a.preventDefault(),a.stopPropagation()))},!1);u.addEventListener("keypress",function(a){Sb||We||!Ze||(a.preventDefault(),a.stopPropagation())},!1);u.addEventListener("keydown",function(a){Sb||We||(Ze&&(a.preventDefault(),a.stopPropagation()),Bf=a.ctrlKey?!0:!1,Mg=a.shiftKey?!0:
!1,Lg=a.altKey?!0:!1,37==a.keyCode?(E(!1),sb(-1),U()):39==a.keyCode?(E(!1),sb(1),U()):32==a.keyCode?G.toggleIsLooping():82==a.keyCode&&a.altKey&&G.resetZoom())},!1);u.addEventListener("mouseenter",function(a){u.focus({preventScroll:!0})},!1);u.style.outlineWidth="0px";u.style.outline="none";Wb=.01745329252;Mb=m=0;Oe=!1;Fe=1;Mf=Db=!1;Ca=Ga=!0;Sf=!1;fb=X=t=0;eg=ef=!1;ff=!0;Wc=null;ib=[];gd=!1;Ha=0;rd=[];Gc=!0;Ja=500;hc=100;$c=2E3;vg=30;uh=0;dg=6E4;Sc=null;Yc=pe=!1;kf=!0;Kc=[];Gd=wb=ia=null;Eg=!1;sa=
Oh=null;Zd=!1;ca=-1;Md=!1;Jf=wf=J=B=1;Vf=!1;O=N=Aa=za=ka=ja=A=n=M=Y=0;bi=!1;Od=ki=!0;Ug=Yf=Vc=!1;qe=nh=-1;$a=[];Bb=0;Wg=!1;qa=null;ed=-1;yg=0;Ne=!1;Va=null;sf=rf=Ta=nc=0;hi=!1;V=0;Ob=og=pg=kd=!1;fh=gh=Pf=Qf=0;ld=bc=!1;Na=[];Na.push("default");Na.push("default");$f="default";Ud=!1;cf="default";lc=null;Ea=[0,0];ce=[0,0];qb=Gg=af=!1;Cd=!0;wa=Cc=null;Eb=dh=!1;nf=!0;ag="default";He=!0;va=[];cc=cg=!1;df="default";bd=!1;Ji=[1,0,0];Ki=[2,2,1];wc=[];Bc=[];Uc=Rd=kb=!1;jf=Kf=0;Ub=Af=yf=y=Fb=null;Vg=0;Ze=!0;
Sb=We=Mg=Lg=Bf=!1;Nd=27;a=p("canvas");a.height=1;a.width=1;bb=a.getContext("2d");bb.imageSmoothingEnabled=!1;Ig=p("canvas");Ve=!1;"string"===typeof b?0>b.indexOf("\n")?Hb(b):c(b.split("\n")):c(b)};this.newBasenames=function(b,a,c,d){kd=!1;Ca=Ga;E(!1);t=d;Si(b,a,c);Gc=!0;Xb()};this.newFilenames=function(b){kd=!1;Ca=Ga;E(!1);Ri(b);Gc=!0;Xb()};this.newOverlayFilenames=function(b){kd=!1;Ca=Ga;E(!1);Ti(b);Gc=!0;Xb()};this.newProbeTable=function(b){bd=!1;q(b.trim())};this.reloadFOF=function(){ha("reload FoF = "+
Sc);xc("r");xd?mj(lj,!1):(Ca=null==xf?!0:Ga,Gc=!0,Xb())};this.getFOF=function(){var b=f.file_of_filenames.trim();G.newFOF(null!=Gd?Gd+b:b,!0)};this.newFOF=function(b,a){G.resetZoom();mj(b,a)};var mj=function(b,a){var c,d,e,f,h=new XMLHttpRequest,l,k,p,r,m,v,n,w=null,z=!1;ji=Bb;kd=!1;Ca=Ga;E(!1);a&&xa(Mb);Bb=t=0;Ba=[];K=Za=null;Eg=!1;Fg=[];for(we=null;Jc.hasChildNodes();)Jc.removeChild(Jc.lastChild);vf=0;Zd=qb=Sd=!1;Da=jd=pc=null;Ua=[];Oc=-1;T=[];var y=!1;if(null==xb||null!=ue)xb=[];ha("new FOF="+
b);kb&&(null!=qc&&(I(qc,!0,"extrap on"),u.style.cursor="default",E(Ca),ab=-1),kb=!1,fa());Eb&&(null!=md&&(I(md,!0,"mark on"),u.style.cursor="default",E(Ca),Wd=-1),Eb=!1,fa());h.onload=function(){var a=this.responseText.split("\n");for(c=0;c<a.length;c++)if(!(2>a[c].length)&&(l=a[c].trim(),ha("FOF: "+l),0!=l.indexOf("#")))if(0==l.indexOf("frame_labels"))m=l.split("="),hb=m[1].split(",");else if(0==l.indexOf("redirect"))for(m=l.split("="),n=m[1].split(","),we=n[0].trim(),d=1;d<n.length;d++){var b=parseInt(n[d],
10)-1;Fg[b]=!0}else if(0==l.indexOf("framenumber_index_values"))m=l.split("="),jg=m[1].split(",");else if(0==l.indexOf("slice")){m=l.split("=");n=m[1].split(",");K=[];for(d=0;d<n.length;d++)K[d]=parseInt(n[d],10);K[2]=K[2]-K[0]+1;K[3]=K[3]-K[1]+1;4<K.length&&(K[6]=K[6]-K[4]+1,K[7]=K[7]-K[5]+1)}else if(0==l.indexOf("fof_extension"))m=l.split("="),w=m[1].trim();else if(0==l.indexOf("probe_table"))m=l.split("="),bd=!1,q(m[1].trim());else if(0==l.indexOf("image_base"))m=l.split("="),ia=m[1].trim();else if(0==
l.indexOf("overlay_base"))m=l.split("="),wb=m[1].trim();else if(0==l.indexOf("high_res_basemap")){m=l.split("=");n=m[1].split(",");jd=[];for(d=0;d<n.length;d++)jd[d]=n[d].trim(),null!=ia&&(jd[d]=ia+jd[d]);Zd=!0}else if(0==l.indexOf("high_res_overlay"))for(m=l.split("="),v=m[1].split("&"),e=0;e<v.length;e++){n=v[e].split(",");Oc=parseInt(n[0].trim(),10)-1;Ua[Oc]=[];for(d=1;d<n.length;d++)Ua[Oc][d-1]=n[d].trim(),Xi(Ua[Oc][d-1],"/")||(null!=wb?Ua[Oc][d-1]=wb+Ua[Oc][d-1]:null!=ia&&(Ua[Oc][d-1]=ia+Ua[Oc][d-
1]));Zd=!0}else if(0==l.indexOf("high_res_zoom")){m=l.split("=");n=m[1].split(",");sa=[];for(d=0;d<n.length;d++)sa[d]=parseFloat(n[d].trim());$b()}else if(0==l.indexOf("hoverzone"))ie(l);else if(0==l.indexOf("hotzone"))Pa(l);else if(0==l.indexOf("hotspot"))z||(gb=null,fb=0,z=!0),Yb(l);else if(0==l.indexOf("toggle_onoff"))m=l.split("="),Hf=m[1].split(",");else if(0==l.indexOf("coordinates"))m=l.split("="),D(m[1]);else if(0==l.indexOf("fof_substitute"))b=l.indexOf("="),n=l.substring(b+1).split(","),
Eg=!0,ii=n[0].trim(),Wi=n[1].trim();else if(0==l.indexOf("map_scale"))m=l.split("="),n=m[1].split(","),Rc=parseFloat(n[0]),$e=1<n.length?parseFloat(n[1]):Rc;else if(0==l.indexOf("times")){m=l.split("=");n=m[1].split(",");for(c=0;c<n.length;c++)xb[c]=parseInt(n[c].trim(),10);y=!0}else{null!=ue&&(b=l.match(ue),null!=b&&2==b.length?(xb.push(parseInt(b[1],10)),ha("+ + + Extrap time = "+b[1]),y=!0):ha("+ + + Cannot parse times using "+ue+" from line: "+l));e=l.indexOf(" ");0>e&&(e=l.length);Ba[t]=l.substring(0,
e).trim();null!=ia&&(Ba[t]=ia+Ba[t]);l=l.substring(e+1);b=l.indexOf('"');0<=b&&(null==hb&&(hb=[]),e=l.substring(b+1),b=e.indexOf('"'),0<=b&&(hb[t]=e.substring(0,b),0==t&&(Va.innerHTML=hb[0])));T[t]=[];b=l.indexOf("overlay");if(0<=b)for(k=l.substring(b),b=k.indexOf("="),0>b&&ha("Cannot find a = sign in "+k),p=k.substring(b+1),k=p.trim(),p=k.split(","),X=Math.max(X,p.length),ha("numOverlays set to "+X),f=0;f<p.length;f++)T[t][f]=p[f].trim(),null!=we&&Fg[f]?T[t][f]=(we+T[t][f]).trim():null!=wb?T[t][f]=
(wb+T[t][f]).trim():null!=ia&&(T[t][f]=(ia+T[t][f]).trim());t+=1}y&&Z(xb);null!=w?(a=new XMLHttpRequest,a.onload=function(){var a=this.responseText.split("\n");for(c=0;c<a.length;c++)2>a[c].length||(r=a[c].trim(),ha("ext_FOF: "+r),0!=r.indexOf("#")&&(0==r.indexOf("hotzone")?Pa(r):0==r.indexOf("hotspot")&&Yb(r)));na()},a.onerror=function(){na()},a.open("get",w+"?"+Math.round(1E5*Math.random()),!0),a.send()):na()};lj=b;h.open("get",b+"?"+Math.round(1E5*Math.random()),!0);h.send()};this.setWindowSize=
function(b,a){if(null!=u){u.style.height=a+"px";u.style.width=b+"px";u.style.padding="0px";jj=a=a-(null!=yf?yf.offsetHeight:0)-(null!=Af?Af.offsetHeight:0)-(null!=Fb?Fb.offsetHeight:0)-Vg*(null!=Ub?Ub.offsetHeight:0);kj=b;var c=a*ta/ua;c>b&&(c=b,a=b*ua/ta);a=Math.floor(a);c=Math.floor(c);Od||(Vc?vd(kj,jj):vd(c,a),fa())}};this.drag=function(b){Eb||(Y=pa.getX(),M=pa.getY(),Sb?(b=r.length-1,r[b].xe=Y,r[b].ye=M,r[b].xp.push(Y),r[b].yp.push(M),r[b].size=Math.round(Math.sqrt(Math.pow(Y-r[b].x,2)+Math.pow(M-
r[b].y,2)))):(n=Y*H,A=M*F,ld=Ob=!1,bc&&(!af||af&&b.shiftKey)?(Pf=n,Qf=A,ld=!0):(Ia&&J!=Jf?(N=ja-n/B,O=ka-A/J,Pc(),ja=Math.round(N+n/B),ka=Math.round(O+A/J),void 0!=$d&&$d(["drag",B,J,ja,ka,n,A,N,O,za,Aa])):Eb||kb||!qb||(wa=null,Cd&&0<=n&&0<=A&&(ba=Be.getImageData(n,A,1,1).data,0!=ba[3]&&(wa=Za[ba[3]-1]))),Vf=!0,U())),fa())};this.resetZoom=function(){B=wf;J=Jf;ca=-1;null!=La&&(I(La,!0,"zoom on"),Ia=!1);ja=n;ka=A;O=N=0;Aa=ua;za=ta;$b();U();Sd&&(qb=!0);void 0!=$d&&$d(["reset",0,0])};this.canTip=function(){var b;
Ob=!1;Y=pa.getX();n=Y*H;M=pa.getY();A=M*F;if(!((Eb||kb)&&A<Ei&&A>Di&&n>Ci)){ja=Math.round(N+n/B);ka=Math.round(O+A/J);if(0!=Bb)for(b=0;b<Bb;b++)if(Ra[b].overlay>=X)ha(" Error...hotzone overlay # "+Ra[b].overlay+" > number of overlays = "+X);else if(w[Ra[b].overlay].checked&&(bb.clearRect(0,0,1,1),bb.drawImage(L[m][Ra[b].overlay],ja,ka,1,1,0,0,1,1),ba=bb.getImageData(0,0,1,1).data,oh=(ba[0]<<16)+(ba[1]<<8)+ba[2],oh==Ra[b].color)){Ob=!0;Fi=Y;Gi=M;Hi=Ra[b].tip;break}if(0!=fb)for(b=fb-1;0<=b;b--)if(null!=
gb[b]){var a=gb[b];if(-1==a.frame||a.frame==m)if(-1==a.overlay||w[a.overlay].checked){var c=!1;if(a.isPan)if(a.isIcon){var d=(a.x0-N)*B-a.w2;var e=(a.y0-O)*J-a.h2;n>d&&n<d+a.width&&A>e&&A<e+a.height&&(c=!0)}else d=(a.x0-N)*B,e=(a.y0-O)*J,n>d&&n<d+a.width*B&&A>e&&A<e+a.height*J&&(c=!0);else n>a.x0&&n<a.x1&&A>a.y0&&A<a.y1&&(c=!0);if(c&&null!=a.tip){Ob=!0;Fi=Y;Gi=M;Hi=gb[b].tip;break}}}fa()}};this.move=function(){if(!kb&&qb&&(wa=null,Cd)){var b=pa.getX()*H,a=pa.getY()*F;0<=b&&0<=a&&(ba=Be.getImageData(b,
a,1,1).data,0!=ba[3]&&(wa=Za[ba[3]-1]))}kb&&2<=ab&&(Y=pa.getX(),n=Y*H,M=pa.getY(),A=M*F);fa()};this.down=function(){Ob&&(Ob=!1,fa());Y=pa.getX();n=Y*H;M=pa.getY();A=M*F;fh=n;gh=A;Pf=fh;Qf=gh;ja=Math.round(N+n/B);ka=Math.round(O+A/J);bc&&(rb(),ce[0]=Ea[0],ce[1]=Ea[1]);Vf=!1;if(Sb){var b={};b.x=Y;b.y=M;b.xe=Y;b.ye=M;b.xp=[Y];b.yp=[M];b.type=Me.value;b.color=Le.value;b.width=Nc.value;b.text=Tb.value;b.size=0;r.push(b)}};this.up=function(b){Ob=!1;if(!Sb){if(kb||Eb){Y=pa.getX();n=Y*H;M=pa.getY();A=M*F;
if(Eb){Wd=1;if(0<Wd&&A/F<hj){if(n/H>gj){va.pop();va.pop();0==va.length&&(Wd=0);fa();return}if(n/H<fj){fa();b=window.open("","Mark Points");b.document.write("<div>Marked Points<br>");for(var a=[],c=0;c<va.length;c+=2)ja=N+va[c]/B,ka=O+va[c+1]/J,rb(),b.document.write(Ea[0].toFixed(4)+","+Ea[1].toFixed(4)+"<br>"),0==c&&(a[0]=Ea[0],a[1]=Ea[1]);nf&&b.document.write(a[0].toFixed(4)+","+a[1].toFixed(4)+"<br>");return}}va.push(n);va.push(A);fa();return}if(3>ab)if(Vb[ab]=n,Gb[ab]=A,ae[ab]=Dg[m],0==ab)ab=1,
xa(oa(t-1)),Kf=1,Fd=null;else{Ni=ae[1]-ae[0];Of=(Vb[1]-Vb[0])/Ni;Qe=(Gb[1]-Gb[0])/Ni;if(null!=mg&&null!=Rc){c=Of*Rc;var d=Qe*$e;a=Math.round(60*Math.sqrt(c*c+d*d));c=Math.atan2(c,-d)/Wb;0>c&&(c+=360);Fd=Lh+rj[Math.round(c/22.5)]+" at "+a+" "+Mh;dj=Vb[0];ej=0<Qe?Gb[0]-15:Gb[0]+30}a=parseInt(se,10);da=Math.round(Math.abs(4*(a+4)/Of));be=Math.round(Math.abs(2*(a+4)/Qe));be<da&&(da=be);120<da?da=120*Math.floor(da/120)+60:90<da?da=120:60<da?da=90:30<da?da=60:15<da?da=30:10<da?da=15:5<da?da=10:2<da?da=
5:0==da&&(da=1);be=ae[1]/da*da+da;Pe=1;Kh&&(Pe=-1);Bi=Of*da;eh=Qe*da;xa(oa(t-1));ab=3;Kf=2}else if(A/F<Ei&&A/F>Di&&n/H>Ci&&3==ab){ac();fa();return}fa()}if(ld)ld=!1,fa();else if(null!=rc&&Ia&&(bc=!1,I(rc,!0,"distance on")),Vf)Vf=!1;else if(b.altKey)G.resetZoom();else if(qb&&null!=wa&&dh)wd(wa,"z");else{Y=pa.getX();n=Y*H;M=pa.getY();A=M*F;if(0!=Bb)for(a=0;a<Bb;a++)if(Ra[a].overlay>=X)ha(" Error...hotzone overlay # "+Ra[a].overlay+" > number of overlays = "+X);else if(w[Ra[a].overlay].checked&&(bb.clearRect(0,
0,1,1),bb.drawImage(L[m][Ra[a].overlay],Math.floor(ja),Math.floor(ka),1,1,0,0,1,1),ba=bb.getImageData(0,0,1,1).data,oh=(ba[0]<<16)+(ba[1]<<8)+ba[2],oh==Ra[a].color)){wd(Ra[a],"z");return}if(0!=fb)for(a=fb-1;0<=a;a--)if(null!=gb[a]){var e=gb[a];if(!(-1!=e.frame&&e.frame!=m||e.fromfile||-1!=e.overlay&&!w[e.overlay].checked)){var f=!1;e.isPan?e.isIcon?(c=(e.x0-N)*B-e.w2,d=(e.y0-O)*J-e.h2,n>c&&n<c+e.width&&A>d&&A<d+e.height&&(f=!0)):(c=(e.x0-N)*B,d=(e.y0-O)*J,n>c&&n<c+e.width*B&&A>d&&A<d+e.height*J&&
(f=!0)):n>e.x0&&n<e.x1&&A>e.y0&&A<e.y1&&(f=!0);if(f){wd(gb[a],"s");return}}}Ia&&(qb=!1,je(b.ctrlKey||Bf||b.which&&3==b.which||b.button&&2==b.button));U();fa()}}};this.wheel=function(b){Zh?sb(b):Ia&&(Y=pa.getX(),n=Y*H,M=pa.getY(),A=M*F,ja=Math.round(N+n/B),ka=Math.round(O+A/J),je(-1==b))};this.toggleAutoRefresh=function(){pe?(I(ad,!1,"autorefresh off"),null!=Sc&&clearInterval(Sc),pe=!1):(I(ad,!0,"autorefresh on"),Sc=setInterval("HAniS.reloadFOF();",dg),pe=!0)};this.toggleLoopRock=function(){Oe?(I(Ee,
!0,"looprock rock"),Oe=!1):(I(Ee,!1,"looprock loop"),Oe=!0)};this.toggleLoopHalt=function(){Db?(I(Ge,!0,"loophalt halt"),Mf=Db=!1):(I(Ge,!1,"loophalt loop"),Mf=Db=!0)};this.toggleExtrap=function(){kb?(null!=qc&&(I(qc,!0,"extrap on"),u.style.cursor=Na.pop(),null!=Lb&&(Lb.disabled=!1),E(Ca),Ia=$h,ab=-1),kb=!1,fa()):(null!=qc&&(kb=!0,Fd=null,Na.push(u.style.cursor),u.style.cursor="crosshair",I(qc,!1,"extrap off"),Ca=Ga,null!=Lb&&(Lb.disabled=!0),Ga=!1,$h=Ia,Ia=!1,G.resetZoom(),ac(),fa()),U())};this.doEnhance=
function(b){if(Rd||Uc){var a=Ya[0].height,c=Ya[0].width;b=parseInt(Fa.value,10);0<=b?(Yg=cb[b],Zg=db[b],$g=eb[b],ah=ve[b],Bc[ub]=b):Bc[ub]=null;var d=a*c*4;for(c=0;c<oc.length;c++)if(Ya[c].gotit){Ya[c].gotit=!1;var e=uf[c].data;var f=Hg[c];if(0>b)for(a=0;a<d;a+=4)e[a]=f[a],e[a+1]=f[a+1],e[a+2]=f[a+2],e[a+3]=f[a+3];else for(a=0;a<d;a+=4)jb=f[a],jb===f[a+1]&&jb===f[a+2]&&(e[a]=Yg[jb],e[a+1]=Zg[jb],e[a+2]=$g[jb],e[a+3]=ah[jb]);id[c].putImageData(uf[c],0,0);Ya[c].gotit=!0}}};this.overClick=function(b){var a;
if(b.target.checked)for(a=0;a<w.length;a++)b.target!=w[a]&&0!=b.target.name&&b.target.name==w[a].name&&(w[a].checked=!1);Cd=!0;for(a=0;a<gc.length;a++)b.target!=w[a]&&Jb(a),null!=Cc&&!Cc[a]&&w[a].checked&&(Cd=!1),null!=Fa&&a===ub&&(Fa.disabled=!w[a].checked);U()};this.toggleIsLooping=function(){Ga?(Ga=!1,I(Lb,!0,"startstop start")):(Ga=!0,I(Lb,!1,"startstop stop"),Mf=Db,Db=!1)};this.toggleZooming=function(){Ia?(G.resetZoom(),I(La,!0,"zoom on")):(I(La,!1,"zoom off"),Ia=!0,null!=rc&&(bc=!1,I(rc,!0,
"distance on")),Sd&&(qb=!0),kb&&G.toggleExtrap())};this.togup=function(b){nh=-1};this.togdown=function(b){var a=Sg.getX();Sg.getY();for(var c=zi,d=0;d<$a.length;d++){if(a>c&&a<c+Yd){if(d==nh)break;if(b.shiftKey){0<=$a[d]&&(E(!1),xa(d));break}a=0;!b.ctrlKey&&0<=$a[d]&&(a=-1);Ka(d,a);nh=d;break}c=c+Yd+Gf}};this.makeMP4=function(){var b=Nb.innerHTML;Ca=Ga;E(!1);Fe=1;xa(oa(Mb));Nb.innerHTML="Working";HME.createH264MP4Encoder().then(function(a){var c,d,e,h,k;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:a.width=
W,a.height=aa,a.frameRate=Math.max(1,Math.round(1E3/Ja)),a.quantizationParameter=Nd,a.initialize();case 2:return U(),a.addFrameRgba(C.getImageData(0,0,W,aa).data),g.yield(new Promise(function(a){return window.requestAnimationFrame(a)}),4);case 4:if(m>=oa(t-1)){g.jumpTo(3);break}sb(1);g.jumpTo(2);break;case 3:a.finalize();Nb.innerHTML=b;c=a.FS.readFile(a.outputFilename);d=f.mp4_prompt;e=f.mp4_filename;null==e&&(e="hanimate.mp4");h=e;if(null!=d&&(h=window.prompt(d,h),null==h))return a.delete(),E(Ca),
g.return();k=document.createElement("a");k.href=URL.createObjectURL(new Blob([c],{type:"video/mp4"}));k.download=h;k.click();a.delete();E(Ca);g.jumpToEnd()}})})};this.makeAniGIF=function(){if(!Sf){var b=Cb.innerHTML;Tf=new GIF({workers:4,debug:!1,quality:10,width:W,height:aa,repeat:0});Tf.on("finished",function(a){Cb.innerHTML=b;var c=f.anigif_prompt,d=f.anigif_filename;null==d&&(d="hanimate.gif");if(null!=c&&(d=window.prompt(c,d),null==d))return;c=document.createElement("a");c.href=URL.createObjectURL(a);
c.download=d;c.click();setTimeout(function(){URL.revokeObjectURL(a)},3E4)});Tf.on("progress",function(a){Cb.innerHTML=Math.round(100*a)+"%"});Ca=Ga;E(!1);Fe=1;Sf=!0;xa(oa(Mb));U();E(!0);Cb.innerHTML="Loading"}};this.doneLoading=function(b){tf=b};this.getCustomButton=function(){return pf};this.dwellChanged=function(b){Xd=b};this.getDwell=function(){return Ja};this.frameChanged=function(b){Lf=b};this.getFrame=function(){return m};this.showFrame=function(b){xa(oa(b));U()};this.zoomChanged=function(b){$d=
b};this.showZoom=function(b){"reset"===b[0]?G.resetZoom():(B=b[1],J=b[2],ja=b[3],ka=b[4],n=b[5],A=b[6],N=b[7],O=b[8],za=b[9],Aa=b[10],Pc(),U())}};
